### ISSUE TITLE
Wrong field used for an object in a loop

### ISSUE THREAD

**Issue by wizbit** [PebbleTemplates/pebble#165]
Looping over a list of field for an object always retrieves the first field. 
It is caused in GetAttributeExpression.java line 86:

    Member member = object == null?null:(Member)this.memberCache.get(object.getClass());

A test is included below: (It currently prints NameName)

    private static class Person
    {
        public String getName() { return "Name"; }
        public String getSurname() { return "Surname"; }
    }
    @SuppressWarnings("serial")
    @Test
    public void testAccessingValueWithSubscriptInLoop() throws PebbleException, IOException {
        PebbleEngine pebble = new PebbleEngine.Builder().loader(new StringLoader()).strictVariables(false).build();

        String source = "{% for attribute in ['name', 'surname']%}{{ person[attribute] }}{% endfor %}";
        PebbleTemplate template = pebble.getTemplate(source);

        Map<String, Object> context = new HashMap<>();
        context.put("person", new Person());

        Writer writer = new StringWriter();
        template.evaluate(writer, context);
        assertEquals("NameSurname", writer.toString());
    }

**Comment by mbosecke** [comment]
Good catch. It looks like it caches the Member object during the first evaluation. It should use the attribute name to break the cache.
