### ISSUE TITLE
Maven snippets in documentation

### ISSUE THREAD

**Issue by SkPhilipp** [PebbleTemplates/pebble#175]
Hey there,

At [http://www.mitchellbosecke.com/pebble/documentation/guide/spring-integration](http://www.mitchellbosecke.com/pebble/documentation/guide/spring-integration) you're ending an `<artifactId>` tag with `</artifact>`. Also on the main usage page you have spaces around the version number, which is weird, my IDE removed them for me.

**Comment by mbosecke** [comment]
Thanks, it's now fixed.
