### ISSUE TITLE
Missing doc for range function

### ISSUE THREAD

**Issue by bjansen** [PebbleTemplates/pebble#178]
I just discovered that there is a `range` function, which is exactly what I needed, but unfortunately it's not listed in the reference here: http://www.mitchellbosecke.com/pebble/documentation

Could you please document it, and maybe check if there are any other undocumented functions/tags/etc?

**Comment by ebussieres** [comment]
Actually it's missing some.

Cache tag
Range Function
Spring extension and a lot of new features (https://github.com/mbosecke/pebble-spring3/pull/5)

**Comment by bjansen** [comment]
Also, the documentation for `max()` contains an example that uses `min()`.

**Comment by mbosecke** [comment]
I've now open sourced the documentation, pull requests are welcome: https://github.com/PebbleTemplates/pebble-docs
