### ISSUE TITLE
Configure latest pebble in spring using xml configuration

### ISSUE THREAD

**Issue by fritzfs** [PebbleTemplates/pebble#180]
Hello!

As the subject says :-)

How can I set up latest pebble in spring using xml configuration?

**Comment by hectorlf** [comment]
Please see this: https://github.com/mbosecke/pebble-spring3/issues/7

It may be time to update the docs with the snippet :)

**Comment by mbosecke** [comment]
Thanks. 

I've now open sourced the documentation, pull requests are welcome: https://github.com/PebbleTemplates/pebble-docs
