### ISSUE TITLE
How do i simply repeat a fragment "n" times?

### ISSUE THREAD

**Issue by ablipan** [PebbleTemplates/pebble#181]
I'm repeating a "star" element for "n" times, but can not find a simple way to do it.
May be the `for` tag could add a simply function, like:

```twig
{% set num = 5 %}
{% for num %}
<i class="fa fa-star"></i>
{% endfor %}
```
result:
```html
<i class="fa fa-star"></i>
<i class="fa fa-star"></i>
<i class="fa fa-star"></i>
<i class="fa fa-star"></i>
<i class="fa fa-star"></i>
```

updated: 
I've added a custom function which combine with the `raw` filter to repeat html fragment.
```twig
{% set num = 5 %}
{{ repeat(num, '<i class="fa fa-star"></i>') | raw}}
```

I'm thinking is there a need for enhancing the `for` tag to achieve the same result.

**Comment by stanislas-m** [comment]
You can use the range function for that (but this one is not documented) :
```twig
{% for i in range(0,5) %}
    <i class="fa fa-star"></i>
{% endfor %}
```

**Comment by ablipan** [comment]
@stanislas-m Thanks ,the `range` function is working fine.
It turned out that a lot stuff is missing in the document. :frowning:

**Comment by derekvandaal** [comment]
I think proper documentation is key to the usage/usability of a project.

I will gladly assist. Is there any way we can contribute?

**Comment by mbosecke** [comment]
I've open sourced the documentation, pull requests are welcome: https://github.com/PebbleTemplates/pebble-docs
