### ISSUE TITLE
ConcurrentModificationException when importing macros in nested parallels blocks

### ISSUE THREAD

**Issue by karlpauls** [PebbleTemplates/pebble#182]
The fix for #159 just passes down the importedTemplates list to the embedded EvaluationContext. This fixes the problem that parallel blocks don't have access to macros imported into the outer context however, now we get a problem in the case where one is importing macros _inside_ the parallels block. This is concurrently modifying the list of importedTemplates (and technically, is leaking inner macros to the outer context).

**Comment by karlpauls** [comment]
I can basically think of two easy ways to fix this. I created a pull request for each. Furthermore, they contain a test for this issue that does repeatable fail for me (depending on your hardware ymmv). 

The difference between the two is that one (the "snapshot") makes it so that the macros included in an inner context are not "leaked" to its outer context while the other (the "copyonwrite") does still "leak".  Personally, I think the "leaking" is not what i would expect so I'd go with the "snapshot" patch but I don't feel very strongly either way. 

Finally, the reason the test is writing in a bit of a roundabout way is that in case of a parallel tag, exceptions during the evaluation just bubble up to the Thread of the Executor (where they get swallowed) -- hence, from the outside (the template.eval) it looks like everything went ok while in reality a swallowed exception might have messed the result up. I think this is a bug in its own right which probably should be addressed in a separate issue/patch.

**Comment by mbosecke** [comment]
Good catch, thanks for both the test and the proposed solutions. I went with the "snapshot" technique but I adjusted where the list is copied so that it only occurs when using the "parallel" tag.
