### ISSUE TITLE
Question about license from Spring Source

### ISSUE THREAD

**Issue by sachinwalia2k8** [PebbleTemplates/pebble#184]
I have raised a ticket with Spring source to natively support pebble. Here is the Jira ticket: https://jira.spring.io/browse/SPR-14062. It seems that they have concern about license. 
@mbosecke If this is something you are OK with then can you update the ticket with the information they are looking for?

**Comment by hectorlf** [comment]
Juergen already said no, sorry @sachinwalia2k8
