### ISSUE TITLE
Variable function argument count

### ISSUE THREAD

**Issue by pun-ky** [PebbleTemplates/pebble#190]
suppose that I want to have a function which grabs one named parameter but is using rest (unknown / unlisted args in method getArgumentNames) to build query string e.g

{{ route(action='action1', params={'a': 'b', 'c': 'd'}) }} -> '/my/action1?a=b&c=d'

but I want to achieve syntax simplification:

{{ route(action='action2', a='b', c='d') }}

I failed while implementing it. Is it even possible? I noticed error "'a' is not a parameter' or sth like that.

**Comment by hectorlf** [comment]
Named varargs in functions is not supported, and AFAIK is not on the planned feature list. If you want a function with a variable number of arguments, only positional access is allowed. The recommended way is the same that you got working (using maps).

**Comment by decebals** [comment]
@pun-ky 
Did you find a solution? I have the same request for [Pippo](https://github.com/pippo-java/pippo/issues/260).

**Comment by decebals** [comment]
I don't know why, but first variant (comment) doesn't work and the second variable works.
What I want to do in my `RouteFunction` is to capture the arguments and to call `Router.uriFor(String routeName, Map<String, Object>parameters)`.
```
{#
<a href="{{ route('quote', {'symbol': {{ stock.symbol }}}) }}">{{ stock.symbol }}</a>
#}
<a href="{{ route('quote', {'symbol': 'IBM'}) }}">{{ stock.symbol }}</a>
```

My `RouteFunction` looks like:
```java
class RouteFunction implements Function {

    private Router router;

    public RouteFunction(Router router) {
        this.router = router;
    }

    @Override
    public List<String> getArgumentNames() {
        List<String> names = new ArrayList<>();
        names.add("routeName");
        names.add("parameters");

        return names;
    }

    @Override
    public Object execute(Map<String, Object> args, PebbleTemplate self, EvaluationContext context, int lineNumber) {
        String routeName = (String) args.get("routeName");
        Map<String, Object> parameters = (Map<String, Object>) args.get("parameters");

        return router.uriFor(routeName , parameters);
    }

}
```

Am I doing something wrong?

**Comment by ebussieres** [comment]
Remove {{ }} in your call to route function around stock symbol

**Comment by decebals** [comment]
@ebussieres 
Thanks!
It's 1:30 AM in Bucharest and maybe it's to late :)
Do you think that the approach is good, and the route function must work with multiple parameters (for example `route('quote', {'symbol': stock.symbol, ''date': date, ... })`)?

**Comment by decebals** [comment]
@ebussieres 
Thanks!
It was 1:30 AM in Bucharest and maybe was to late :)
Do you think that the approach is good, and the route function must work with multiple parameters (for example `route('quote', {'symbol': stock.symbol, ''date': date, ... })`)?
