### ISSUE TITLE
Pebble and SpringBoot

### ISSUE THREAD

**Issue by dmarko484** [PebbleTemplates/pebble#198]
I'm using Pebble with SpringBoot. Is there a smart way how to create links to Controllers so final URL contains e.g. context etc. ? I mean something like http://www.thymeleaf.org/doc/tutorials/2.1/thymeleafspring.html#building-uris-to-controllers ...

**Comment by hectorlf** [comment]
The short answer is: not yet. That's something the spring extension needs, but hasn't been tackled yet.

**Comment by ebussieres** [comment]
It's something I've already done where i'm working but as a custom extension. I can definitely add it in the spring extension. Something like an href function which adds the context path

```
<a href="{{ href('/foobar') }}>Example</a>
```
