### ISSUE TITLE
Cannot use for tag to iterate through Array List.

### ISSUE THREAD

**Issue by gbanda** [PebbleTemplates/pebble#202]
Hi All,

I have been trying to iterate through an Array List of items with {% for item in items %} syntax to no avail.
Keeps throwing java.lang.UnsupportedOperationException
	at java.util.AbstractMap.put(AbstractMap.java:209)
	at com.mitchellbosecke.pebble.template.Scope.put(Scope.java:53)
	at com.mitchellbosecke.pebble.template.ScopeChain.put(ScopeChain.java:61)
	at com.mitchellbosecke.pebble.template.EvaluationContext.put(EvaluationContext.java:162) exception.

Tried with primitive arrays, maps, many types of List implementations, always this is the result. When doing an iterable test, the array list returns true, so I think it should be iterable using the for tag. Am I doing something wrong? Please find the code below.

 PebbleTemplate template = pebbleEngine.getTemplate("{% if menuItems is iterable %}{% for menuItem in menuItems %}" +
                " \"{{ menuItem }}\" this" +
                "{% endfor %}{% else %}nope{% endif %}");
        StringWriter writer = new StringWriter();

        List<String> menuItems = new ArrayList<>();
        menuItems.add("menu item1");
        menuItems.add("menu item2");
        menuItems.add("menu item 3");

        template.evaluate(writer, Collections.<String,Object>singletonMap("menuItems", menuItems));
        System.out.println(writer);

**Comment by nicky9door** [comment]
The stacktrace suggests that pebble is trying to add additional values to the scope map.  Collections.singletonMap is an immutable map which does not allow for additional insertion. Try using a hashmap instead

**Comment by gbanda** [comment]
hi nicky9door,

Already tried. HashMap, ArrayList, Set, primitive arrays, arrays of strings arrays of integers LinkedList etc were tried to no avail.

**Comment by mbosecke** [comment]
Like @nicky9door mentioned, it is known to not work with immutable collections. Can you provide an example where you are using a mutable collection and it still doesn't work?

**Comment by mbosecke** [comment]
Closing. The for loop does not support immutable collections.
