### ISSUE TITLE
How could I get spring context in TokenParser or Function?

### ISSUE THREAD

**Issue by qiutiaoming** [PebbleTemplates/pebble#204]
Because I am using Spring security to security my web app, and want to implement a tag named PermitTokenParser  to check whether if a user have permitted  to some resources . so how could I get spring context in Pebble tag/function ? 

``` twig 
{% permit 10000 %}
       You are here...
 {% endpermit %}
```

or how could I  access the {{ request }} from TokenParser or Function ?

Thanks.

**Comment by ebussieres** [comment]
In pebble-spring, you can access the following variable

- HttpRequest
- HttpSession
- HttpResponse
- Application context

Everything is in the documentation : http://www.mitchellbosecke.com/pebble/documentation/guide/spring-integration#access-to-spring-beans

**Comment by qiutiaoming** [comment]
Thanks, @ebussieres ,I found ViewUtil class in pebble-spring ,but this is not released .
