### ISSUE TITLE
Issue with i18n function and spring boot

### ISSUE THREAD

**Issue by sachinwalia2k8** [PebbleTemplates/pebble#207]
When using pebble in Spring boot there is an issue with i18n function as described below:

1. Declare a property called testKey with value as testValue001 inside application.properties
2. In any of the html template refer to this value using following expression:
{{i18n("application","testKey ")}}
3. In spring boot commandline overwrite the properties by defining an external application.properties as follows:
java -jar -Dspring.config.location=/path/to/external/application.properties SampleApp.jar
4. Set the value of testKey inside application.properties as "testValue002"
5. In your html the value will still show as testValue001.

I am not sure if this is the limitation of pebble that it cannot combine and override the value from external application.properties. People using pebble may find this as limiting because it is very common to use external application.properties for overriding based on profile and environment.

**Comment by mbosecke** [comment]
The `i18n` function doesn't know anything about spring or any sort of hierarchical configuration. It is a very simple function that delegates to Java's [Resource Bundle](https://docs.oracle.com/javase/7/docs/api/java/util/ResourceBundle.html)

If you're using the `pebble-spring3` or `pebble-spring4` there is another function called `message` which is very similar to the built-in `i18n` function but it delegates to springs `[MessageSource](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/context/MessageSource.html)` instead. I haven't tested it, but I suspect that it may behave how your expecting it to.
