### ISSUE TITLE
Accessing class lists

### ISSUE THREAD

**Issue by met68** [PebbleTemplates/pebble#213]
I am also posting this here, as the Google forum seems dead:

I am using a variable called errors which is a List<Error> to pass form validation errors back to the template after validation. The Error class has two properties: String field and String message.

So under each html form input element, I want to display the appropriate error message, if any. For instance, under the form input element with name="username", I want to display any error.message in errors where error.field == "username".

I currently use a Pebble macro which I include in each form to accomplish this, where for each html form input element I call the getErrors(errors, field) macro and where the field parameter is the name of the html input elemet (e.g. username):

{% macro getErrors(errors, field) %}
  {% if errors is not empty and errors is iterable %}
    {% for error in errors %}
      {% if error.field == field %}
        \<p class="text-danger error"\>{{- error.message -}}\</p\>
      {% endif %}
    {% endfor %}
  {% endif %}
{% endmacro %}

And while this works fine, it does not seem very efficient nor elegant.

Is there instead a way to do something like the following  under each html input element?

{% if errors.field["username"] is not empty %}
  {{ errors.field["username"].message | first }}
{% endif %}

I have tried the above and some variations of it, but without luck.

Is anything like this possible in Pebble and if not, is it maybe worth adding this feature in future?

**Comment by mbosecke** [comment]
Are you able to change the structure of the data being passed to the template? 

If my understanding is correct this is what you are currently passing:
```
Error usernameError = new Error();
usernameError.setField("username");
usernameError.setMessage("username can not be null");

List<Error> errors = new ArrayList<>();
errors.add(usernameError);
```

Instead maybe send it as a Map with key/value pairs that can be referenced in the template:
```
Map<String, String> errors = new HashMap<>();
errors.put("username", "username can not be null");
```
which would allow you to look up individual errors using nothing more than `{{ errors["username"] }}`

**Comment by met68** [comment]
Thank you for your response and yes, you understood correctly. I originally used a HashMap exactly as you describe, but for me this throws an exception. Does not accept the square brackets. This may be related to the fact that I am using Pebble as the template engine in the Spark framework and this still uses Pebble version 1.4.4. as a dependency. I understand that they are in the process of upgrading this as we speak and hopefully, when they are done, I will be able to use the approach as described by you. In the meantime, I will work with my hack. I still think it would be useful, if items in class lists could be accessed directly. Would this be feasible, maybe in a future realease?

**Comment by mbosecke** [comment]
Yup the older version would explain why you're getting errors. If I remember correctly, I think it was version 1.5 that introduced the square bracket notation.

> I still think it would be useful, if items in class lists could be accessed directly

I think what you're describing creates very hard-to-understand template code, very dissimilar to java, and it's not something that can't be replicated with existing functionality. If I'm understanding correctly, writing ` errors.field['username']` would implicitly loop through the list of items and for each item, check it's "field" attribute and if it's equal to "username" it will return that item (assuming there's only one item that matches this criteria which is a big assumption). The notation itself conflicts with the notation used to retrieve items from a map, so no, I don't see this being implemented.
