### ISSUE TITLE
Configuration to keep the first newline after a pebble tag 

### ISSUE THREAD

**Issue by electrotype** [PebbleTemplates/pebble#214]
Is there a reason why the first newline after a pebble tag is ignored? I guess it has something to do with HTML, but I'd like to use Pebble as a templating engine for other formats than HTML.

Let's say I have a template which is :

```
{{param1}}
{{param2}}
```

How can I make Pebble generate :

```
val1
val2
```

As is, with the newline?
Is there a configuration to keep the first newline after a pebble tag?

**Comment by mbosecke** [comment]
Duplicate of #125
