### ISSUE TITLE
Access value from a Set

### ISSUE THREAD

**Issue by ChinesePeanuts** [PebbleTemplates/pebble#218]
Hi,

Is there any way to access a Object in a Persistent Set ?

I have an Object called `module` and for each of my modules, I have an attribute which is a `Set` of `program` (another Object)

I wish I could access the first program of the list by doing this `{{ module.programs[0] }}` but I can't.
Still, I can display the set by doing this `{{ module.programs }}`.

Is there any workaround ?

Thanks in advance

**Comment by stanislas-m** [comment]
Hello,
I think this issue is related to your problem: #196

**Comment by stanislas-m** [comment]
Thinking about it, you can't ask for the first item of a Set (there is no order in a Set).
You can try to use a List instead, since its index is an int. That way it will be easier to solve.

**Comment by ChinesePeanuts** [comment]
Oh well, just realized that...
I'll try with a List, but let's say that I wish to access any value of this Set, how should I proceed ?
Thanks for your help

**Comment by mbosecke** [comment]
There isn't an easy way to access a particular value from a Set. That's not a pebble problem, that's a problem with Sets in general. Your needs probably require a different data structure.
