### ISSUE TITLE
Raw filter should call toString on non-string inputs

### ISSUE THREAD

**Issue by marctinkler** [PebbleTemplates/pebble#222]
Currently, the raw filter does not touch the input if it is not a string.  This makes it impossible to
output raw JSON if the input object is a JSONObject (for example).

I'd propose using something like this instead in RawFilter:

public Object apply(Object inputObject, Map<String, Object> args) {
  return inputObject == null ? "" : new SafeString(inputObject.toString());
}

**Comment by ebussieres** [comment]
Just made a PR for this #229

**Comment by mbosecke** [comment]
#229 has been merged.
