### ISSUE TITLE
Passing the content of a block section to an included fragment

### ISSUE THREAD

**Issue by electrotype** [PebbleTemplates/pebble#224]
Let's say I have a main `layout.html` template which has a "body" block and also includes a `header.html` fragment. Every concrete pages extend `layout.html` and define their custom "body" `block.

My problem is that the `header.html` template displays a menu, but some concrete pages need to add a submenu, just below it!

Is it possible for the main `layout.html` template to "retrieve" such submenu content from a concrete page and _pass it_ to the included `header.html`?

A dummy example would be :

 `layout.html` :

```
...
{% set subMenu = {% block subMenu %}{% endblock %} %}
{% include "./header.html" with {"subMenu", subMenu} %}
{% block body %}{% endblock %}
```

 `concretePage.html` :

```
{% extends "./layout.html" %}
...
{% block subMenu %}
    <div>concrete page submenu</div>
{% endblock %}

{% block body %}
    <div>concrete page body</div>
{% endblock %}
```

 `header.html` :

```
<div>main menu</div>
{% if subMenu is not empty %}
    {{subMenu | raw}}
{% endif %}
```

Is something similar to this possible?
Thanks!

**Comment by tboyce021** [comment]
The way I've worked around this is to wrap it in a macro:
```
{% macro subMenu() %}
    {% block subMenu %}{% endblock %}
{% endmacro %}

{% set subMenu = subMenu() %}
```
You then run into the issue of the macro not having the same scope as the template and have to work around that though.
