### ISSUE TITLE
Support for evaluating in-memory templates

### ISSUE THREAD

**Issue by kibertoad** [PebbleTemplates/pebble#228]
Currently Pebble only supports loading templates from files. It would be useful to be able to pass entire template as String, provide variable map and get the evaluation result.

**Comment by ebussieres** [comment]
You should take a look to all unit tests in Pebble to achieve that. It uses a StringLoader

```
PebbleEngine pebble = new PebbleEngine.Builder().loader(new StringLoader()).build();

String source = "{% if foobar %}true{% else %}false{% endif %}";
PebbleTemplate template = pebble.getTemplate(source);

Map<String, Object> context = new HashMap<>();
Writer writer = new StringWriter();
template.evaluate(writer, context);
```

**Comment by kibertoad** [comment]
Thank you, that did work! Could you please add this example to the documentation?

**Comment by mbosecke** [comment]
It's not designed to be used for production because a lot of features, ex.
inheritance, don't work when using this Loader.
