### ISSUE TITLE
Feature Request: Sandbox Extension

### ISSUE THREAD

**Issue by menostos** [PebbleTemplates/pebble#234]
Is there a way to disable invocation of getClass() ?

It currently seems possible to access this on existing context variables.

**Comment by mbosecke** [comment]
Can you elaborate on your particular use case and why this would be helpful?

I'm assuming this is a security concern. Twig uses a ["sandbox" extension](http://twig.sensiolabs.org/doc/api.html#sandbox-extension) that allows them to whitelist which tags, filters, functions, and variable properties can be accessed within a template. This is something I've wanted in Pebble for awhile, would it solve your use case?

**Comment by menostos** [comment]
Yes this is mostyl due to security concerns. 
A sandbox extension would definitly solve that issue.

**Comment by ebussieres** [comment]
getClass is now disabled by default (v2.5)
