### ISSUE TITLE
Feature Request: String Interpolation

### ISSUE THREAD

**Issue by DanStout** [PebbleTemplates/pebble#235]
Twig offers a feature called [string interpolation](http://twig.sensiolabs.org/doc/templates.html#string-interpolation) which they describe like so:

> String interpolation (#{expression}) allows any valid expression to appear within a double-quoted string. The result of evaluating that expression is inserted into the string:

Example:

```
{{ "Hello #{name}, you have #{msgs} messages, #{msgs - read} unread" }}
```

Compared to the current form:

```
{{ "Hello "+ name + ", you have "+ msgs + "messages, " + (msgs - read) + "unread" }}
```

I was planning to implement this in a filter that would work like:

```
{{ "hello #{name}" | interp }}
```

Where the input would be parsed, and any expressions would be evaluated using a separate PebbleEngine using a StringLoader. I didn't see a convenient way of accessing evaluating the string template with the correct context (I was planning to get it via EvaluationContext "_context" argument to the filter, but that didn't really work out). 

I feel like this might be better implemented as part of the engine core rather than an extension both for ease of implementation and because having to add " | interp" after every interpolated string kind of cancels out the reason to use it in the first place.

**Comment by mbosecke** [comment]
I would definitely be on board with this being a core feature, implemented similarly to how Twig has done it. Pull requests are welcome.

**Comment by DanStout** [comment]
OK. I started working on it, and will make a pull request in the near future.
