### ISSUE TITLE
Feature Request: Escape Delimiters 

### ISSUE THREAD

**Issue by liniu** [PebbleTemplates/pebble#237]
Template content contains delimiters as follows ,it throws unexpected token "OPERATOR" of value ".." 
`There are two primary delimiters used within a Pebble template: {{ ... }} and {% ... %}.  ... `

how to escape {{,}} ,{% and %}

**Comment by stanislas-m** [comment]
Did you try the verbatim tag? http://www.mitchellbosecke.com/pebble/documentation/tag/verbatim

**Comment by liniu** [comment]
verbatim can solve the problem, thank you @stanislas-m, but in some cases, I just want to escape {{ or }}   .an extreme example:
```
{% for text in contents %}   
	{% if text contains '{{' %}	  
	   	{{text}} contain  {% verbatim %}{{{% endverbatim %} ...some other expressions
        {% endif%}  
 {% endfor %}
``` 
maybe the following expression is more simple:
```
{% for text in sections %}   
	{% if text contains '{{' %}	  
	   	{{text}} contain \{{ , ...some other expressions
        {% endif%}  
 {% endfor %}
```

**Comment by mbosecke** [comment]
It's not perfect but I believe an alternative solution would be to use the variable syntax with a literal string as the variable, i.e. `{{ '{{' }}`. 

```
{% if text contains '{{' %}   
    {{text}} contains  {{ '{{' }}
{% endif%}  
```
