### ISSUE TITLE
Potential NPE in PebbleException

### ISSUE THREAD

**Issue by Glamdring** [PebbleTemplates/pebble#243]
PebbleException allows a null line number. However, when getLineNumber is called, it assumes the Integer field is non-null and may fail with NPE trying to convert it to int https://github.com/PebbleTemplates/pebble/blob/8f011d3402dacf7555e1240245287cd55586da23/src/main/java/com/mitchellbosecke/pebble/error/PebbleException.java#L39 

Proposed solution: changed int to Integer

**Comment by ebussieres** [comment]
Fixed in next release
