### ISSUE TITLE
Add support for Java8 java.time types

### ISSUE THREAD

**Issue by glapa** [PebbleTemplates/pebble#244]
Currently `date` filter supports only old `Date` type. I think that it would be great to move forward and allow to use new time types (`LocalDate`, `LocalDateTime`, `ZonedDateTime` and `Instant`).

**Comment by mbosecke** [comment]
Good idea; it'll have to be for Pebble 3.0 which will be the first version that supports java 8 at all.

**Comment by hectorlf** [comment]
I have a joda-time extension laying around that would be trivial to convert to java 8 time api, but it's fairly complex in comparison to the current date filter, so I'd like a little guidance here.
Functionality that can be ported:
- Date formatting filter with support for pattern, locale, timezone and style
- Date instantiating function (basically a "new Date()") with support for parsing text
- A few block tags to allow to change the default locale and timezone
What do you think, interested in any of these?

**Comment by ebussieres** [comment]
Done via #251
