### ISSUE TITLE
JRE version mismatch problem

### ISSUE THREAD

**Issue by sureez** [PebbleTemplates/pebble#246]
Hello sir,
We are using pebble template engine for preparing message. We are facing problem like our development and production servers are running in 1.6 but pebble jar is compiled in 1.7. So we stuck in the testing phase. Please help us fix this problem?

Error we received : java.lang.UnsupportedClassVersionError: JVMCFRE003 bad major version; class=com/mitchellbosecke/pebble/loader/Loader, offset=6

Pebble POM:
<plugin>
	<artifactId>maven-compiler-plugin</artifactId>
	<version>2.3.2</version>
	<configuration>
		<source>1.7</source>
		<target>1.7</target>
	</configuration>
</plugin>

**Comment by sureez** [comment]
I am pretty new to github. Can i use this link(https://github.com/PebbleTemplates/pebble/releases) to download source code of that specific version and compile with jdk1.6. OR is there any other links i can download jre1.6 compiled version of pebble jar?

**Comment by ebussieres** [comment]
Fork the code, checkout it and rebuild it with a jdk6 version. Maybe it
isn't compatible though and you will have some refactoring to do.

**Comment by sureez** [comment]
There are few refactoring had to be done to compatible with jdk6. All testcases are successfully build.
Thanks. Closing this issue.
