### ISSUE TITLE
Possibility to hook into some thing like tag missing ?

### ISSUE THREAD

**Issue by snimavat** [PebbleTemplates/pebble#255]
I am planning to integrate pabble into grails framework.
Grails supports tag libraries, and i would like to make it possible to use existing grails tags into pabble.

For that, i need some way to delegate the handling to grails tags.

However as far as i understand, each custom pabble tag has to be defined at compile time (with parser) and can handle a single tag only.

What i am looking for is, some way to hook into pabble, so whenever some tag is used in template, but is not explicitely defined, my tag/parser gets called and there i can do some hacks and call grails tags and render output.

is this even possible ?

For example, handlebars java supports handlebars.registerHelperMissing which can be used to hook in and handle all missing tags not explicitely registerd and delegate to whatever thirdparty solution i want.

**Comment by thomashunziker** [comment]
I do not know Grails in details. If the tags do not exists at compile time of the template you will not be able to implement this. The fundamental problem here is that the parser needs to know the tags which should be recognized. 

However you may create dynamically a pebble engine which knows all your tags and then you can parse the template with the modified pebble engine.

**Comment by snimavat** [comment]
> However you may create dynamically a pebble engine which knows all your tags and then you can parse the template with the modified pebble engine.

Can you point me to some docs/example or any thing that can help me with this?

**Comment by thomashunziker** [comment]
You simply need to modify the PebbleEngine with your custom tags. In essence you have to create an extension which holds the corresponding custom tags. The rest works like the following:

````
PebbleEngine.Builder builder = new PebbleEngine.Builder();
builder.extension(extension);
PebbleEngine engine = builder.build();
PebbleTemplate compiledTemplate = engine.getTemplate("home.html");

Map<String, Object> context = new HashMap<>();
context.put("name", "Mitchell");

Writer writer = new StringWriter();
compiledTemplate.evaluate(writer, context);

String output = writer.toString();
````

The extension has to be created dynamically. The details for that really depends on Grails. So I am not able to help you. The extension is an interface. So you can return what ever you like. It is important to understand once the PebbleEngine has been built changes within the extension will not be reflected anymore.

**Comment by snimavat** [comment]
Okay, i will look into this and see how can i hook grails tags using extension.
