### ISSUE TITLE
Possible to extent the .attribute access?

### ISSUE THREAD

**Issue by bckfnn** [PebbleTemplates/pebble#258]
Is it possible to extend the the [dot notation](http://www.mitchellbosecke.com/pebble/documentation/guide/basic-usage#variables) to support other types of variables in addition to POJO and Map.

In my use case the variables are vert.x [JsonObject](http://vertx.io/docs/apidocs/io/vertx/core/json/JsonObject.html) and [JsonArray](http://vertx.io/docs/apidocs/io/vertx/core/json/JsonArray.html), which use getValue(..) instead of get(..).

As far as I can tell the supported variable types are hardcoded in GetAttributeExpression and can not be extended

**Comment by nicky9door** [comment]
Looking at the docs for those objects, they have a getter to expose the underlying map/list so you should be able to do something like `jsonObject.map['property']` or `jsonArray.list[index]` to retrieve your property.

An alternative would be to write a pebble filter which takes the property name and calls the getValue method on the input object

**Comment by michaelmosmann** [comment]
I did an pull request to make it extendable .. https://github.com/PebbleTemplates/pebble/pull/280

**Comment by ebussieres** [comment]
I have merged the pull request #281 in branch v3. I think that we will release it only on v3 since I will use this PR to remove the DynamicAttributeProvider which was causing some performance issues
