### ISSUE TITLE
Support for velocity variable syntax?

### ISSUE THREAD

**Issue by jchappelle** [PebbleTemplates/pebble#259]
I'm evaluating pebble as a replacement for Velocity in our project. I really like the inheritance and it seems easy to use.

Our templates can be customized by users but we ship out defaults in the classpath. Will I have to convert all our templates to use the {{foo}} variable syntax? Currently our variables are the velocity ${foo} syntax. Is there anyway to customize this?

Thanks in advance!

**Comment by ebussieres** [comment]
In the PebbleEngine Builder, you can set a Syntax object. I have never tried to modify it, but you can check it out.

**Comment by jchappelle** [comment]
That's awesome! It worked!

```
ClasspathLoader loader = new ClasspathLoader();
loader.setPrefix("templates/");
Syntax.Builder builder = new Syntax.Builder();
builder.setPrintOpenDelimiter("${");
builder.setPrintCloseDelimiter("}");
PebbleEngine engine = new PebbleEngine.Builder().syntax(builder.build()).loader(loader).build();
```
It's hard to give criticism here but my only tiny complaint is that Syntax.Builder's setters don't return itself for method chaining. Again not a big deal but figured I'd mention it.

I'm really liking this so far. Keep up the good work!

**Comment by ebussieres** [comment]
I totally agree with you. Syntax builder should be modified to return itself. You can make a PR if you wish
