### ISSUE TITLE
Caching template to disk

### ISSUE THREAD

**Issue by thclev** [PebbleTemplates/pebble#261]
Hi, is it possible to cache the template to disk, specifically before it gets evaluated?

Use case: template is constant, but resource bundles / locales / context variables change and application is restarted.

In the above case the template is the same, but not the evaluate step since context / locales might have changed.

PebbleTemplate itself isn't Serializable.

**Comment by ebussieres** [comment]
There's already a template cache in the PebbleEngine. You can customize it when building PebbleEngine. Version 2.x uses guava cache and it's gonna be caffeine for version 3.x. You can configure it as you wish (size, time to live, etc.).

If you really wish to always write cache to disk and reload it from disk (which I really don't suggest), you can try to extend guava to overflow to disk https://www.javacodegeeks.com/2013/12/extending-guava-caches-to-overflow-to-disk.html
