### ISSUE TITLE
Loop Continue Break

### ISSUE THREAD

**Issue by sdemedia** [PebbleTemplates/pebble#264]
Hi,

Is it possible to continue or break out of a for loop? If not, what would be the best way to implement this functionality?

Thanks.

**Comment by ebussieres** [comment]
I don't think so ... and I wouldn't advice it. Don't put too much logic in your view layer, you should handle it in your controller

**Comment by sdemedia** [comment]
In an ideal world that would be my choice but since this is not an option at the moment, is it possible to write my own tag/function to get this functionality? Is it easy to do or is it going to be complex? 

I have notice that twig has and conditional option for the foreach tag which is not supported in Pebble at the moment, will this be supported in a future release?

<ul>
    {% for user in users if user.active %}
        <li>{{ user.username|e }}</li>
    {% endfor %}
</ul>

**Comment by ebussieres** [comment]
You can try to define a new tag by defining a TokenParser in a custom extension. Check [here](http://www.mitchellbosecke.com/pebble/documentation/guide/extending-pebble#tags) for information on how to extend pebble

You can check the [ForTokenParser](https://github.com/PebbleTemplates/pebble/blob/master/src/main/java/com/mitchellbosecke/pebble/tokenParser/ForTokenParser.java))
