### ISSUE TITLE
bean method call doesn't support primitive argument type

### ISSUE THREAD

**Issue by thomasguo** [PebbleTemplates/pebble#268]
I read post issues and know someone have submit similar issue before.  unfortunately it occurs again in my application.
For example , I have a java class name Pet: 
`
public class Pet(){
   int age;
   public int add(int increment){
       return age + increment;
   }
}
`
And I have a Pet instance named pet in template context.  Code like:
`{{ pet.add(2) }}`

It simply does'nt work.   Please help.

**Comment by ebussieres** [comment]
Related issue is #196 but it was for map. It has just been fixed and is gonna be in the next release. Your case still doesn't work.

**Comment by decebals** [comment]
I use as workaround the variants:
- create a pebble function wrapper
- use static method (expose an Utils class that contains static methods)

It would be nice to have the possibility to call a public method with parameters like in the first comment.

**Comment by ebussieres** [comment]
Fixed via #341
