### ISSUE TITLE
Pebble common macro file, use within other java projects.

### ISSUE THREAD

**Issue by batuhancaglayan** [PebbleTemplates/pebble#277]
Hello Mitchell,

I am trying to create a project which includes macros (a simple library for re-usable ui controls (macros) ). I will use this project within other java projects. How can i import a macro file from external java project. (or jar).
please help me.

Thank you,

**Comment by yanxiyue** [comment]
implement your own customize template loader

**Comment by batuhancaglayan** [comment]
@yanxiyue thanks for your answer, do you mean ServletLoader (class.) This class uses single prefix and suffix property. can i create a loader which uses multiple prefix? or how can i implement and use custom loader. thanks.

**Comment by jochen777** [comment]
with our spring-boot projects, it's enough to create an own spring-boot project (let's call it "base") and include the common templates there under "/templates/..."
Now make a maven project out of this and reference this out of the other projects.

maybe with:
`<dependency>
      <groupId>yourgroup</groupId>
      <artifactId>base</artifactId>
      <version>0.0.1-SNAPSHOT</version>
    </dependency>`

**Comment by yanxiyue** [comment]
@batuhancaglayan  no, I mean that you can  implement com.mitchellbosecke.pebble.loader.Loader, for customizing your template loading logic.  

eg:  
suppose your macros was put under "commonMacros", 
```java
public class  MyLoader implements Loader<String> {
    @Override
    public Reader getReader(String templateName) throws LoaderException {
        if (templateName.startWith("commonMacros/")) { 
            // load from your macros jar
        } else {
            // ...
        }
    }
   // ...
}
```
you can import your macros like this:

```
{% import "commonMacros/macro.peb" %}
```
------ 
sorry for my poor english :)

**Comment by batuhancaglayan** [comment]
@yanxiyue wow, good solution, i debuged getReader method and saw templateName parameter value as macro name,
i will try implement like your example and i will load macros from jar, i will try tonight and write feedback thank you very much again.

**Comment by batuhancaglayan** [comment]
@yanxiyue Thank you very much. Problem solved helps with your code. :D 
added this code under  if (templateName.startsWith("commonMacros/"))  condition

Thread.currentThread().getContextClassLoader().getResourceAsStream("utils/macroUtil.html.twig");

Thanks
