### ISSUE TITLE
broken encoding in 2.4.0

### ISSUE THREAD

**Issue by vitalyster** [PebbleTemplates/pebble#278]
any new parameters to read templates in UTF-8?

**Comment by yanxiyue** [comment]
if you use FileLoader or ClasspathLoader, 'UTF-8' is default encoding.  
you could specify encoding with Loader#setCharset method.
if you use pebble-spring-boot-starter, you could specify encoding in application.yml::

```
pebble:
    encoding: UTF-8
```

**Comment by vitalyster** [comment]
I'm using `com.mitchellbosecke.pebble.loader.ServletLoader` and it seems to be broken in 2.4. I see it have UTF-8 charset by default, but templates are rendered incorrectly, while in 2.3 it works good

**Comment by yanxiyue** [comment]
I can not reproduce your case, could u give more information or upload your code?

**Comment by vitalyster** [comment]
@yanxiyue well, here is the demo project https://github.com/vitalyster/pebble278

**Comment by yanxiyue** [comment]
@vitalyster i have a try with your code.  you can fix this problem by adding charset to viewResolver likes below:
```java
viewResolver.setCharacterEncoding("UTF-8");
```
u are right, 2.4 is different from 2.3, which dropped the default charset.

**Comment by vitalyster** [comment]
https://github.com/PebbleTemplates/pebble/blob/master/src/main/java/com/mitchellbosecke/pebble/loader/ServletLoader.java#L24 - but it is still there

**Comment by yanxiyue** [comment]
the difference is not in ServletLoader, is in PebbleView.
2.3 PebbleView.java Line 53:
``` java
private String characterEncoding = "UTF-8";
```
2.4 PebbleView.java L49:
```java
private String characterEncoding;
```

**Comment by vitalyster** [comment]
Ah, ok, so if this is intended change (in https://github.com/PebbleTemplates/pebble-spring4 project btw), it should be mentioned in documentation/examples

**Comment by ebussieres** [comment]
It's a bug. Please log the issue in pebble-spring4 project.

Thanks !
