### ISSUE TITLE
Offline documentation

### ISSUE THREAD

**Issue by Xianguang-Zhou** [PebbleTemplates/pebble#282]
Is there a PDF or EPUB documentation for offline reading?

**Comment by cjbrooks12** [comment]
It's not currently supported, though it should be relatively easy to implement, if there's good Java libraries to convert HTML to PDF/EPUB. 

The wiki plugin was directly inspired by GitBook so conversion to PDF is an idea I've wanted to have in Orchid for a long time, and I'd be happy to implement it. But I've never done any HTML->PDF conversion in Java and I don't really know where to start, so I would appreciate any help if you have suggestions for libraries or anything like that.

**Comment by bjansen** [comment]
I believe an offline *HTML* documentation would be easy, though.

**Comment by cjbrooks12** [comment]
I've gotten Orchid generating the wiki contents as a PDF! This will be available in the next major release, and I'll make the necessary changes here to support it when it's released.

**Comment by ebussieres** [comment]
Great news !
