### ISSUE TITLE
Call static method within Pebble

### ISSUE THREAD

**Issue by MrPowerGamerBR** [PebbleTemplates/pebble#289]
(this is just a feature request)

One thing that I've never figured out is how to call static methods within Pebble, while I can call objects functions if I add them to the template context, static methods... well, can't be added to a context.

**Comment by ebussieres** [comment]
It isn't possible to call static functions and cannot be done

**Comment by MrPowerGamerBR** [comment]
Awwww, this sucks.

Well, I still can do the old "create a object with functions that calls static methods and then pass the object instance to Pebble" way.
