### ISSUE TITLE
Operator precedence is not working as expected

### ISSUE THREAD

**Issue by jochen777** [PebbleTemplates/pebble#290]
I think the operator precedence is not working properly:

Consider this model:
`t = true;
f = false;`

And consider this template:
`{% if not f and not t %}
This should not be displayed
{% endif %}`

... But the result is, that "This should not be displayed" IS displayed.

If I use parentheses 

`{% if (not f) and (not t) %}
This should not be displayed
{% endif %}`

it works as expected

**Comment by ebussieres** [comment]
Fixed via 9cd75833a0f1a79611ccacdab2d4a9c01d1b639e

**Comment by jochen777** [comment]
cool! Sourcecode change is much cleaner, than I expected! Thank you!
