### ISSUE TITLE
Allow all variable names to be retrieve from ScopeChain/Scope

### ISSUE THREAD

**Issue by zemian** [PebbleTemplates/pebble#291]
Hi, 

I want to write a custom function to return all the variable names available from the current context (it's very valuable for debugging purpose). I can get ScopeChain from EvaluationContext, but there is no method exposed to retrieve all the keys from each Scope's backingMap. I got around this by using Java reflection so far, but it will be nice to have this available from the API.

Thanks,
Zemian

**Comment by axeld** [comment]
I second this, not just for debugging purposes. I've implemented a function that allows expression evaluation within my application (it comes with its own expression language); there is currently no way to pass on the scope chain as bindings.

**Comment by ashokgelal** [comment]
@ebussieres Can we have this please? This seems very trivial to add (just a function) and I don't see and downside of this. I can send a PR but I'm not sure whether you want this implemented or not.

**Comment by ebussieres** [comment]
Sure, just make a PR and I'll gladly review it
