### ISSUE TITLE
For tag does not support java.util.Enumeration?

### ISSUE THREAD

**Issue by zemian** [PebbleTemplates/pebble#292]
There are some popular API such as HttpServletRequest.getAttributeNames() still return java.util.Enumeration, and yet Pebble not able to loop through these without extra work of converting into a Iterable first. Would be nice to support this out of the box.

Thanks,
Zemian

**Comment by hectorlf** [comment]
Will work on it this weekend.

**Comment by hectorlf** [comment]
Please bear in mind that looping over Enumerations might perform poorly because we need to loop it two times if you use the size or "reverse index" properties.

**Comment by ebussieres** [comment]
@hectorlf build is broken with your commit

**Comment by hectorlf** [comment]
Fixed, thanks!
