### ISSUE TITLE
Render content on-demand

### ISSUE THREAD

**Issue by lmajano** [PebbleTemplates/pebble#295]
Is there a way to use pebble to render but not using a file template. Meaning, I have twig syntax content coming from the database and I want that rendered.

**Comment by nicky9door** [comment]
You can create a PebbleEngine that uses StringLoader as the loader implementation.  Doing this will cause ```engine.getTemplate()``` to use the template name as the contents to be parsed.

Alternatively, you can create your own Loader implementation that uses some sort of database key to retrieve the template and return a StringReader containing the content.

**Comment by lmajano** [comment]
Thanks for the feedback @nicky9door. However, I think this would be great core addition to have the ability to pass in template contents and render it out.  Thoughts on making this core?

**Comment by nicky9door** [comment]
StringLoader already is in core, i.e. you could do something like the following without writing any Pebble specific classes:

```
StringWriter renderedTemplate = new StringWriter()
String templateContents = getTemplateFromDb(); 
Map<String, Object> context = createContext()
PebbleEngine engine = new PebbleEngine.Builder().loader(new StringLoader()).build();
PebbleTemplate template = engine.getTemplate(templateContents);
template.evaluate(renderedTemplate, context);
System.out.println(renderedTemplate.toString())
`````

Perhaps a `evaluateTemplateLiteral` could be added directly to PebbleEngine but I think the advantage to the current method is that it keeps the pebble 'flow' consistent

**Comment by lmajano** [comment]
I like this approach, but it requires me to keep two singleton pebble engines in my code. One for string loader and another for on disk template loaders.  Not a biiiiig deal, but essentially, it would be cool if I would pass the literal evaluations to a single engine.  Food for thought?

Just for background.  We are writing an extension of pebble for CFML and the ColdBox MVC Framework: https://www.forgebox.io/view/cbt

We use it now to load templates from disk by convention, but we also have a Modular CMS platform which stores contents as well on DB.  So having both the file and literal approaches are fantastic. We have mocked it for now, by actually writing the templates to disk and then sending them to pebble.

So far it works fantastic and we would love to support Pebble development in any way we can.

**Comment by nicky9door** [comment]
You might be able to use a `DelegatingLoader` which checks the filesystem first and falls back to a `StringLoader`.  This might be problematic though if your template literals end up being an existing file path

I wouldn't be opposed to a `getLiteralTemplate` method on PebbleEngine that returns a string based PebbleTemplate so that the flow remains the same

**Comment by lmajano** [comment]
If you guide me @nicky9door I would be delighted to send you a pull request for it. This way, I can familiarize myself with the innards of Pebble and contribute in any which way I can.

**Comment by nicky9door** [comment]
The decision to add this change would ultimately be up to @mbosecke.

As far as the actual code required, I think the easiest way to implement this would be to change [PebbleEngine.getTemplate](https://github.com/PebbleTemplates/pebble/blob/bd94a2b61b4b7a6909ad3a36035417ed40695bb3/src/main/java/com/mitchellbosecke/pebble/PebbleEngine.java#L100) to a private method that takes the loader as a parameter.  Then you could create two methods:

  * getTemplate(String templateName) -> Calls the private method using `this.loader`.  This ensures existing code works
  * getLiteralTemplate(String template) -> Calls the private method using a StringLoader()

The only thing that needs to be considered is whether the literal templates should be cached and if so, whether they should use the same cache as the traditionally loaded templates

**Comment by hectorlf** [comment]
I agree with @nicky9door, using two engines will make things easier for you. Very likely you aren't going to want the same caching rules for the two types of templates. That being said, if this were to be added, it wouldn't happen in the 2.x branch.

**Comment by lmajano** [comment]
@hectorlf are you planning a 3.0 release? I have not seen much activity lately?
If so, where can we see the roadmap of features.

FYI: jTwig supports this feature, which is incredibly useful for CMS adaptations.

**Comment by ebussieres** [comment]
Fixed
