### ISSUE TITLE
Implementation of Pebble instead of JSP

### ISSUE THREAD

**Issue by baddaralishah** [PebbleTemplates/pebble#297]
I am implementing a basic CRUD application. I have used JPA Modeler and getting default JSP as template language. I want to replace it with Pebble. Can some one help me? Do JPA Modeler detect pebble as template language or need some configurations? Please Note, I have developed a Maven project.

**Comment by hectorlf** [comment]
There's a high change that Pebble is not supported by any tool. The http://www.mitchellbosecke.com/pebble/documentation/guide/installation guide and the http://www.mitchellbosecke.com/pebble/documentation/guide/basic-usage is all you need to understand how to use it.
