### ISSUE TITLE
Spring MVC Form Validation 

### ISSUE THREAD

**Issue by fdanismaz** [PebbleTemplates/pebble#300]
I have enabled Bean Validation on the server side. Like the following:

```
        @PostMapping(value = "/save", params = "add")
	public String save(Model model, @Valid UserModel user, BindingResult result) {
		if (!result.hasErrors()) {
			this.userService.save(user);
			return "redirect:/user/list";
		}
		else {
			return "user/UserList";
		}
	}
```

But, {{ hasErrors("formKullanici") }} returns false even if the binding result hasErrors on the server side. And I couldn't succeed to show the validation errors on the page.

**Comment by jochen777** [comment]
you have to put the boolean "hasErrors" in the form. 
Example:
`... 
else {
  model.addAttribute('formerror', result.hasErrors());
  return "user/UserList";
`

.. and within the template

`{% if formerror %} This form has an error! {% endif %}

**Comment by fdanismaz** [comment]
I see your solution but there seems to be a better way under the integration with Spring page:
[http://www.mitchellbosecke.com/pebble/documentation/guide/spring-integration] there are several methods for validations and error messages like

{{ hasErrors('formName' }}
{{ hasGlobalErrors('formName' }}
{{ hasFieldErrors('formName', 'fieldName' }}

but these methods returns false..

**Comment by jochen777** [comment]
ah - you're right. I never used this, so - sorry, I can't help you with that...

**Comment by ebussieres** [comment]
Did you declare the springExtension bean ? I suspect that you didn't

**Comment by fdanismaz** [comment]
Sure, the springExtension bean is defined.

**Comment by mohamedb** [comment]
I get the same error when I misspelled the form name. in your example "formKullanici" is not present
