### ISSUE TITLE
Allow class literals

### ISSUE THREAD

**Issue by ddimtirov** [PebbleTemplates/pebble#302]
Some API's require class literals, which are currently impossible to express in Pebble.

For example, consider:

```
// assume <T> T lookup(Class<T> type)
billOfMaterials.lookup(com.acme.airplane.Wing).length
```

Ideally, we would be able to import the class, so we won't have to spell the fully qualified name at every usage:

```
{# @pebimport type="com.acme.airplane.Wing" #}
```

Finally, aliasing can come in handy when one needs to use 2 classes witht he same short name.

```
{# @pebimport name="PlaneWing" type="com.acme.airplane.Wing" #}
{# @pebimport name="BirdWing" type="com.acme.bird.Wing" #}
```

Tangentially related to #289

**Comment by hectorlf** [comment]
I've also bumped with similar issues in my Stripes extension, but I'll ask anyway: do you have a real use case for that?

**Comment by ddimtirov** [comment]
The use case is code generation, where we have a richly typed domain model (as opposed to map of lists).

**Comment by hectorlf** [comment]
O_O

I see Pebble as a text output tool and have a hard time visualizing what you intend to do. Could you please elaborate with an actual example?

**Comment by ddimtirov** [comment]
Please close. This is rather old and meanwhile I've solved my need in different way.
