### ISSUE TITLE
Is it wokring with gradle ?

### ISSUE THREAD

**Issue by gorkemgunal** [PebbleTemplates/pebble#305]
Is it wokring with gradle ? Do you have any guide?

**Comment by jansorg** [comment]
@gorkemgunal Of course it is, it's just a regular dependency...

**Comment by gorkemgunal** [comment]
Thanks, I already used it for a mail template. But I have a new problem: How can I use a .css file for html template.  What is the location and declaration of a stylesheet file ?

**Comment by jansorg** [comment]
I don't think that this is related to Pebble. For mail you either have to use an externally hosted stylesheet or you have to inline it.

**Comment by hectorlf** [comment]
Thanks @jansorg
