### ISSUE TITLE
DynamicAttributeProvider has no context or named attributes

### ISSUE THREAD

**Issue by axeld** [PebbleTemplates/pebble#306]
`DynamicAttributeProvider` currently has no means to access the EvaluationContext, and therefore also cannot access the ScopeChain. Also, is there any reason it does not support named arguments?

**Comment by axeld** [comment]
Would a patch that breaks compatibility by extending the `DynamicAttributeProvider` interface to get the EvaluationContext (and template, for that matter) be acceptable?

**Comment by hectorlf** [comment]
If it breaks a released interface, then it'll have to wait until the next major.

**Comment by ebussieres** [comment]
DynamicAttributeProvider has been removed in 3.0. Instead, you can now define a custom attributeResolver in the extension (see https://github.com/PebbleTemplates/pebble/wiki/extending-pebble#attribute-resolver-v3-only).

I'll check to add the evaluationContext has a parameter in the interface

**Comment by ebussieres** [comment]
Just added the EvaluationContext as a parameter to AttributeResolver (452f54abc2d0cd5d3599374ef39f8182feebd865)

**Comment by axeld** [comment]
Great, thanks!
