### ISSUE TITLE
How to trim all spaces?

### ISSUE THREAD

**Issue by mystdeim** [PebbleTemplates/pebble#309]
How to use Pebble in "production mode" I mean remove all spaces between tags and make one line?

It seems that I should use "newLineTrimming(true)" but anyway I get \n in my rendered document

**Comment by KarolS** [comment]
newLineTrimming only removes line breaks after tags, so 
```
{{ 'thing1' }}
{{ 'thing2' }}<br>
{{ 'thing3' }}
```
renders as 

```
thing1thing2<br>
thing3
```
As far as I know, there are no other trimming features.

**Comment by mystdeim** [comment]
Does this feature exist?
```
<div>
  {{ 'value' }}
</div>
```

Render as:
```
<div>value</div>
```

**Comment by jochen777** [comment]
you can try this: 

`{{- 'value' }}`

so add a dash

**Comment by mystdeim** [comment]
But if I have:

```
<div>
  <div>
    ...
  </div>
</div>
```

Is it possible to trim everything between tags?

```
<div><div>...</div><div>
```

**Comment by jochen777** [comment]
as far as I know, this is not possible. I recommend to use gzip compression on your server. this will save more space (and gain speed) and you keep your formatting on the client.
