### ISSUE TITLE
Cache API

### ISSUE THREAD

**Issue by a1730** [PebbleTemplates/pebble#310]
Hi!
Thanks for a fabulous, fast template engine.
Would it be possible to implement caching against a cache interface rather than the current dependence on Guava? This would allow the user to swap cache libraries as desired. It looks like it is trivial to extract the Guava Cache interface, and replace the reference to Immutable with java.util.Map.
Thank you.

**Comment by decebals** [comment]
See https://github.com/PebbleTemplates/pebble/issues/294. Add a vote.
