### ISSUE TITLE
Undocumented 'replace' filter

### ISSUE THREAD

**Issue by pun-ky** [PebbleTemplates/pebble#314]
I have implemented own 'replace' filter but on the runtime, I noticed that it is already implemented in core. 
Please document all missing filters on page: http://www.mitchellbosecke.com/pebble/documentation

Thank you very much! Regards.

**Comment by ebussieres** [comment]
Thanks I just added it 

https://github.com/PebbleTemplates/pebble-docs/tree/7d952b2d9b70f281c7dbb7972fc1eea881d34908

**Comment by pun-ky** [comment]
thanks!
