### ISSUE TITLE
How to change value of Variable after declare it in Thymeleaf ?

### ISSUE THREAD

**Issue by knavadiya** [PebbleTemplates/pebble#316]
here I have declared variable with name someVariable and assign default value 10 after that I am changing value of variable but I am geting error

How to change value of Variable after declare it in Thymeleaf ?

```

<p th:with ="someVariable=10">
              <p th:text ="someVariable=${someVariable}+${someVariable}"> </p>
              <p th:text ="${someVariable}"> </p>
</p>
```

**Comment by knavadiya** [comment]
<p th:with ="someVariable=10">
              <p th:text ="someVariable=${someVariable}+${someVariable}"> </p>
              <p th:text ="${someVariable}"> </p>
</p>

**Comment by knavadiya** [comment]
<p th:with ="someVariable=10">
              <p th:text ="someVariable=${someVariable}+${someVariable}"> </p>
              <p th:text ="${someVariable}"> </p>
</p>

**Comment by JosefBoukal** [comment]
Hi @knavadiya 

This is a not a Thymeleaf project so, please, ask Thymeleaf related questions/issues at [the correct GitHub project.](https://github.com/thymeleaf)
