### ISSUE TITLE
Blocks in include files

### ISSUE THREAD

**Issue by deelo55** [PebbleTemplates/pebble#318]
Is it possible to have a block in an include file.
For example:

head.peb:
```
<head>
<title>{% block title %}{% endblock %}</title>
</head>
```

parent.peb:
```
<!DOCTYPE html> <html> {% include "include/head" %} 
<body> 
{% block content %}{% endblock %}  
</body>
 </html>
```

child.peb:
```
{% extends "parent.peb" %}
{% block title %}My Title{% endblock %}

{% block content %}HELLO{% endblock %}
```

**Comment by colesico** [comment]
As far as I know this is impossible due the bad design. The included file has its own independent blocks hierarchy.
You can pass a string variable as the title value
