### ISSUE TITLE
Embed tag

### ISSUE THREAD

**Issue by deelo55** [PebbleTemplates/pebble#319]
At the moment, there is no implementation of the Twig embed tag. This really hinders the ability to reuse code as include tags cannot contain any blocks.

Additionally the set tag in twig allows arbitary blocks of html:

`{% set foo %}     <div id="pagination">         ...     </div> {% endset %}`
--
This would also be a useful feature to implement.

Is there anyone actively working on this project? Its a great templating engine....would be a shame to see it die.

**Comment by hectorlf** [comment]
Could you provide a use case for the two issues? I've had a look at the embed tag in Twig and I have a hard time figuring out what would I use it for. So, please, an example of a layout you're trying to achieve would be great. And the same goes for the set tag.

**Comment by cjbrooks12** [comment]
I've actually used the `embed` tag heavily in PHP Twig, and would love to see it implemented here. The way I have used it is in a CMS setting, to implement a 'wrapper" or "container" element that can be reused horizontally across many different layouts. For example:

**layouts/page.peb**
```twig
{% extends 'layouts/base.peb' %}
{% block main %}
    <div id="main">
    {% embed 'includes/container.peb' %}
        // uses default header and content, but overrides footer for static page CTA
        {% block pageFooter %}{% endblock %}
    {% endembed %}
    </div>
{% endblock %}
{% endextends %}
```

**layouts/post.peb**
```twig
{% extends 'layouts/base.peb' %}
{% block main %}
    <div id="main">
    {% embed 'includes/container.peb' %}
        // uses default footer and content, but overrides header to show breadcrumbs, tags, author, etc.
        {% block pageHeader %}{% endblock %}
    {% endembed %}
    </div>
{% endblock %}
{% endextends %}
```

**includes/container.peb**
```twig
{% block pageHeader %}{% endblock %}
{% block pageContent %}{% endblock %}
{% block pageFooter %}{% endblock %}
```

Compare this to the equivalent without the 'embed' tag:

**layouts/page.peb**
```twig
{% extends 'layouts/base.peb' %}
{% block main %}
    <div id="main">
        <div id="container">
            {% include 'includes/container/header.peb' %}
            {% include 'includes/container/content.peb' %}
            // you can override footer here, but there's no way to know what the "normal" thing to do here is, plus you have to manually bring over the wrapper markup
        </div>
    </div>
{% endblock %}
{% endextends %}
```

**layouts/post.peb**
```twig
{% extends 'layouts/base.peb' %}
{% block main %}
    <div id="main">
        <div id="container">
            // you can override header here, but there's no way to know what the "normal" thing to do here is, plus you have to manually bring over the wrapper markup
            {% include 'includes/container/content.peb' %}
            {% include 'includes/container/footer.peb' %}
        </div>
    </div>
{% endblock %}
{% endextends %}
```

The `embed` tag makes it really simple to not only enforce consistent markup patterns, but also reduces the number of templates needed to make it happen while also providing much greater flexibility.

**Comment by hectorlf** [comment]
Well, I see the point with the number of templates, but TBH, this embed thing looks like an afterthought. Something like: "oh shit, this inheritance model works awfully bad for templates, let's try to workaround it". In other words, what you're looking for is Apache Tiles. Anyway, would this embed tag supersede macros? (I guess so, but honestly, I hate them and never use them)

**Comment by cjbrooks12** [comment]
I'm with you on macros, I've never found them to be very useful, but I don't think it supersedes macros. Macros are more like isolated-scope user-defined functions, but `embed` is more of a flexible `include` and inherits the parent evaluation context. Embed is really just like the `extends` tag, but is used for page fragments rather than whole pages.

**Comment by deelo55** [comment]
I strongly believe there is a strong use case for embed. Alternatively, if blocks could be overwritten by child template.

Use Case:

**base.peb**
<!DOCTYPE html>
<html>
{% include "head" %}
<body>
{% block content %}{% endblock %}
</body>
</html>

**head.peb**
{% block meta %}{% endblock %}

**home.peb**
{% extends "base" %}

{% block meta %}
<meta name="description"
      content="hello world"/>
<meta name="robots" content="noindex"/>
{% endblock %}

{% block content %}
hello world
{% endblock %}

Currently this doesn't work as home cannot overrwrite the pebble block meta. There are workarounds but they are not convenient and a bit messy. Either embed or allowing child templates to propagate blocks would help the situation. This is a simple example but there are more complicated use cases where these kind of blocks can really help.

**Comment by deelo55** [comment]
Hi, any chance we can implement this feature?
We are really struggling with code duplication at the moment without this feature.

**Comment by ebussieres** [comment]
@deelo55 it's an open source project. You're free to provide a pull request with a new feature that meets your need.
