### ISSUE TITLE
Anyone want to be paid to add feature

### ISSUE THREAD

**Issue by deelo55** [PebbleTemplates/pebble#321]
Hi,
I need someone to add some features to this framework. If you’re interested ping me. 
D

**Comment by hectorlf** [comment]
Hmmm, but why don't you explain what you need? It might be the perfect thing we were waiting for!

**Comment by deelo55** [comment]
I mentioned in a previous post that files which are included cannot contain blocks. For example:

Is it possible to have a block in an include file.
For example:


head.peb:
```
<head>
<title>{% block title %}{% endblock %}</title>
</head>
```

parent.peb:
```
<!DOCTYPE html> <html> {% include "include/head" %} 
<body> 
{% block content %}{% endblock %}  
</body>
 </html>
```

child.peb:
```
{% extends "parent.peb" %}
{% block title %}My Title{% endblock %}

{% block content %}HELLO{% endblock %}
```


This is a really limiting factor for me right now. I have a major project in JSF/Facelets that I want to migrate to Spring MVC/Pebble but I cannot do it as Pebble doesn't support this functionality.
Also the embed tag from Twig would be useful.

**Comment by DirkLachowski** [comment]
With no maintainer right now and no pr merged since last year, how should a new feature find it's way back to the codebase?

**Comment by ebussieres** [comment]
I have a workaround for you: 

head.peb:
```
<head>
<title>{{title}}</title>
</head>
```

parent.peb:
```
<html> 
{% block title %}{% endblock %}  
<body> 
{% block content %}{% endblock %}  
</body>
 </html>
```

child.peb
```
{% extends "parent.peb" %}

{% block title %}{% include "head.peb" with {'title': 'MY TITLE'}%} {% endblock %}

{% block content %}HELLO{% endblock %}
```

**Comment by deelo55** [comment]
Hi...thanks for the suggestion but thats not really ideal as every child template now has to have that long verbose line which is repeating the same code over and over. 
The child template should do one thing only and thats define the title.

For example, imagine you wanted to change the name of head.peb...you would have to go into every child template to edit it.

**Comment by ebussieres** [comment]
You're welcome to submit a pull request for your feature then

**Comment by deelo55** [comment]
Unfortunately I dont have a solution for this. If someone wants to do this I'm happy to pay for the development costs (with in reason!). Would be good if the maintainer could confirm they would accept this.

Thank you
