### ISSUE TITLE
Support for Spring 5 WebFlux reactive in Spring Boot 2

### ISSUE THREAD

**Issue by hectorlf** [PebbleTemplates/pebble#333]
With the new focus on reactive from Spring 5 and Spring Boot 2, Pebble is now at a disatvantage. Any newcomer to Spring that wants to try the reactive support will be forced to use Freemarker or Thymeleaf.

**Comment by mikaelhg** [comment]
Suggestion: change the issue title to "Support for Spring 5 WebFlux reactive in Spring Boot 2 autoconfiguration".

**Comment by hectorlf** [comment]
We could very well close this issue, as it will probably never be implemented.

**Comment by ThanosFisherman** [comment]
Why not though? This is a vital feature for those who use non blocking web frameworks.

**Comment by ebussieres** [comment]
Any help would be appreciated on this one

**Comment by ebussieres** [comment]
I've just added basic support for Spring 5 WebFlux reactive in Spring Boot 2. It's gonna be available in next release
