### ISSUE TITLE
Incorrect code in example on how to create a function

### ISSUE THREAD

**Issue by chamakits** [PebbleTemplates/pebble#336]
I noticed that the example provided on how to create functions has a mistake in it.

* File with issue: documentation/guide/extending-pebble.md
* Class with mistake: FibonnaciStringFunction

Specifically, calling 'put' instead of 'add' on a list, and implementing an interface as if it was a function call.

Not capable of create pull request on wiki, hence this issue.

Below, find a correct version of what the 'FibonnaciStringFunction' class example should look like:

```
public FibonnaciStringFunction implements Function {

	@Override
	public List<String> getArgumentNames() {
		List<String> names = new ArrayList<>();
		names.add("length");
		return names;
	}

	@Override
	public Object execute(Map<String,Object> args) {
		Integer length = (Integer)args.get("length");
		Integer prev1 = 0;
		Integer prev2 = 1;

		StringBuilder result = new StringBuilder();

		result.append("01");

		for(int i = 2; i < length; i++){
			Integer next = prev1 + prev2;
			result.append(next);
			prev1 = prev2;
			prev2 = next;
		}
		return result.toString();

	}
}
```

Regards and keep it up.

**Comment by ebussieres** [comment]
Thanks I've changed it. It kinda sucks from github that we cannot create PR for wiki files. Hope it's gonna be fixed soon.

**Comment by cjbrooks12** [comment]
@ebussieres If you'd be interested, I've recently released a new tool for generating documentation for Java projects, [Orchid](https://orchid.netlify.com). Its a static site generator (like Jekyll but much better, especially for Java projects) so we can host the official Pebble docs on Github Pages, and it is based on Pebble templates so it would be a great example of what can be done with Pebble. 

In addition to just managing a wiki, Orchid can also generate Javadocs, and we could also auto-generate pages for all the tags/functions/filter/etc. included in Pebble by default, so we know it is always up-to-date. If you'd be interested, I'd love to get Pebble set up with Orchid so we can better manage the docs as a community.

**Comment by hectorlf** [comment]
@cjbrooks12 even if the full docs remain as a wiki, we need a landing site for GitHub Pages. Please open an issue to track it.

**Comment by cjbrooks12** [comment]
Yup, that's exactly what I was thinking. I'll open an issue, and should have an MVP for this done sometime this week for review.
