### ISSUE TITLE
Version 3 SNAPSHOT availability

### ISSUE THREAD

**Issue by ebussieres** [PebbleTemplates/pebble#339]
Hi everyone,

I just released a SNAPSHOT of next major version (3.0.0-SNAPSHOT) for both pebble and pebble-spring in the snapshot repository of sonatype. If anyone is interested in trying it, you can just add the following code in your pom.xml to retrieve SNAPSHOT versions

```
  <repositories>
    <repository>
      <id>sonatype-public</id>
      <name>Sonatype Public</name>
      <url>https://oss.sonatype.org/content/groups/public</url>
      <snapshots>
        <enabled>true</enabled>
      </snapshots>
    </repository>
  </repositories>
```

After that, just change your pebble dependency to 3.0.0-SNAPSHOT
```
      <dependency>
        <groupId>io.pebbletemplates</groupId>
        <artifactId>pebble</artifactId>
        <version>3.0.0-SNAPSHOT</version>
      </dependency>
```
Waiting for your comments on it !

**Comment by decebals** [comment]
Can you write few words about what is new in version 3. Thanks!

**Comment by ebussieres** [comment]
Sure 

- Java 8
- Macros have access to all variables within the template and are no longer restricted to a "local scope"
- New signature for filters/functions/tests that accepts the PebbleTemplate, EvaluationContext, and line number
- Converted EvaluationContext to an interface with limited access to the underlying implementation
- A "null" used as a boolean expression now throws an error if strict variables is true, treated as "false" otherwise
- Improved error reporting
- Java8 Date API support on date filter
- Replace guava cache with caffeine
- Add String Interpolation (#235)
- Add the possibility to extend attribute access (#258)
- Remove DynamicAttributeProvider

You can also track v3 milestone here : https://github.com/PebbleTemplates/pebble/milestone/5

**Comment by nullstrike** [comment]
Hi, I'm new to this templating engine.
I'm struggling how to use this template engine.

I got few questions if it's okay (hopefully you can forgive me, if I'm asking here)
Do I need to configure something or it is like other template engines that are auto-configured?
I'm trying to work this with Spring Boot but I have difficulty implementing this, do you have any instructions for spring boot?

**Comment by ebussieres** [comment]
Check the spring and spring-boot guide on the wiki https://github.com/PebbleTemplates/pebble/wiki/documentation

**Comment by ebussieres** [comment]
Did anyone try v3 ?

**Comment by slandelle** [comment]
@ebussieres I did. Works fine for me, thanks for the great work! Then, I don't have an extensive test suite, what I'm mostly interested in is providing Pebble support with "Replace guava cache with caffeine". I'll try to check the perf test suite this week.

**Comment by bgunnink** [comment]
Are there any plans to get Pebble 2.5.x and 2.6.x into Maven Central?  The last release available is 2.4.0.

**Comment by cjbrooks12** [comment]
They are up on MavenCentral now, the `groupId` has changed to [`io.pebbletemplates`](https://mvnrepository.com/artifact/io.pebbletemplates/pebble). We have been unable to reach the original creator who holds the publishing keys and so we cannot publish new artifacts to that organization anymore. Moving forward, `io.pebbletemplates` will be the new home of Pebble.

**Comment by slandelle** [comment]
@ebussieres I ran the benchmark from https://github.com/mbosecke/template-benchmark and I have sad news:

2.4.1-SNAPSHOT
```
Benchmark          Mode  Cnt      Score     Error  Units
Pebble.benchmark  thrpt   50  27689,273 ± 303,484  ops/s
```

3.0.0-SNAPSHOT
```
Benchmark          Mode  Cnt      Score     Error  Units
Pebble.benchmark  thrpt   50  24641,075 ± 252,389  ops/s
```

hence 11% drop :(

**Comment by ebussieres** [comment]
Can you compare with version 2.6.1-SNAPSHOT ?

**Comment by slandelle** [comment]
2.4.1-SNAPSHOT was my local fork with the PRs I've already submitted.

2.4.0:

```
Benchmark          Mode  Cnt      Score     Error  Units
Pebble.benchmark  thrpt   50  23562,814 ± 326,440  ops/s
```

2.5.0-SNAPSHOT (slightly better):

```
Benchmark          Mode  Cnt      Score     Error  Units
Pebble.benchmark  thrpt   50  25578,615 ± 515,133  ops/s
```

2.6.1-SNAPSHOT:

```
Benchmark          Mode  Cnt      Score     Error  Units
Pebble.benchmark  thrpt   50  24857,613 ± 307,358  ops/s
```

**Comment by slandelle** [comment]
I'll do some profiling tomorrow.

**Comment by slandelle** [comment]
@ebussieres 

(on my Linux box, more powerful than my laptop):

2.6.1-SNAPSHOT:

```
Benchmark          Mode  Cnt      Score     Error  Units
Pebble.benchmark  thrpt   50  30562.791 ± 232.068  ops/s
```

with #348 + #350:

```
Benchmark          Mode  Cnt      Score     Error  Units
Pebble.benchmark  thrpt   50  32241.146 ± 259.919  ops/s
```

**Comment by ebussieres** [comment]
@slandelle Thanks for looking at it !

**Comment by slandelle** [comment]
@ebussieres Even though Pebble 3 is not stable yet, do you think it would be possible to release beta versions on central? I'd rather depend on instable versions than maintaining a fork :(

**Comment by ebussieres** [comment]
@slandelle Yes it's a good idea. I have some issues running mvn test on my box that I should take care of. It works flawlessly on branch 2.x but doesn't work on branch 3.0. Once it's resolved, i'm gonna pusblish a BETA version on maven central

**Comment by slandelle** [comment]
> I have some issues running mvn test on my box that I should take care of

fixed by #352

**Comment by ebussieres** [comment]
Just released a beta version 3.0.0.BETA01

**Comment by slandelle** [comment]
Awesome, thanks a lot!!!

**Comment by ebussieres** [comment]
I'm going to release version 3.0 at the end of the week. I didn't receive a lot of feedback so here's your last chance !

**Comment by cjbrooks12** [comment]
I just got around to doing a bunch of testing with it last week, and it's all working out really well. No major issues or regressions that I've noticed, and I'm using most out-of-the-box features at least once. 

Getting a good performance boost with it over 2.6 as well. I use it for my static site generator, and it immediately dropped build times from and average of 30 seconds to 22, and got as low as 8 seconds on a warm cache.

**Comment by stevespringett** [comment]
Reading through the milestones for v3 and from what I gather, the existing templates created for 2.x will continue to work with 3.x correct? There also appears to be additional capabilities in templates when used in v3, but all existing template should work, correct?

**Comment by ebussieres** [comment]
Yes. You can try it with version 3.0.0.BETA01
