### ISSUE TITLE
Optimize for in-memory Writers

### ISSUE THREAD

**Issue by slandelle** [PebbleTemplates/pebble#351]
Pebble's output abstraction is `java.util.Writer` that can only write chars or Strings.
When inserting numerical values, Pebble spends quite some time computing String representations of those values, including allocating and GC'ing those Strings.
Now, when `Writer` actually works in memory and is backed by an `AbstractStringBuilder`, it would be possible to directly append numbers into the underlying buffer and save those Strings allocations.
Such optimization is pretty straightforward for `StringWriter` (it exposes the buffer with `getBuffer`) but it might be nice to introduce an interface for custom `Writer`s.

**Comment by slandelle** [comment]
Another possibility would be to use an abstraction for what Pebble writes into that's broader than Writer that enforces String/chars (and of course still provide an implementation on top of Writer).
@ebussieres WDYT?

**Comment by ebussieres** [comment]
If you think that we can optimize performance with one of these solutions, go for it.

**Comment by slandelle** [comment]
Cool, will do!

**Comment by slandelle** [comment]
@ebussieres I would need you to first merge my other PRs ;-)

**Comment by ebussieres** [comment]
@slandelle Done

**Comment by slandelle** [comment]
@ebussieres Thanks!

**Comment by ebussieres** [comment]
@slandelle Can we do something too for pebble-spring in PebbleView class ?

**Comment by slandelle** [comment]
Correct me if I'm wrong, but PebbleView writes into `HttpServletResponse#getWriter` and I guess the implementation of this Writer is vendor specific. So I don't think there's a lot to optimize here with the current Pebble API design.

The major flaw of Pebble, at least on Java 8, is that it's based on `Writer`, hence String/chars. This is convenient for tests and cute benchmarks but in the real world, you want to write **bytes** on a socket.
If Pebble were to take an `OutputStream` instead, `TextNode` (which are usually +80% of the payload) could cache the decoded bytes and save lots of CPU cycles. BTW, I'm not sure the current char array caching as any value (at least, it has not with StringWriter on Java 8).

Then, maybe Java 9's new String implementation is a game changer, I haven't tested Pebble there yet.
