### ISSUE TITLE
Fishy code in ExpressionParser#parseStringExpression

### ISSUE THREAD

**Issue by slandelle** [PebbleTemplates/pebble#354]
From https://github.com/PebbleTemplates/pebble/commit/96a6a408a8b5676a9452cf768c791a3c2d1464b2#diff-52cfe38e86555a836f583ea72ce8224dR337 that was introduced in 3.0 branch, obviously `nextCanBeString` is always true.

cc @DanStout

**Comment by ebussieres** [comment]
Fixed via 90729911c951857f12dbbfbf29e829533315a0b4
