### ISSUE TITLE
Import original benchmark into PebbleTemplates organization

### ISSUE THREAD

**Issue by slandelle** [PebbleTemplates/pebble#359]
I don't think it's worth maintaining benchmarks for other libraries (best way to go into flame wars IMHO), but it would be great to have an official set of benchmarks to test Pebble performance.

See https://github.com/mbosecke/template-benchmark/blob/master/src/main/java/com/mitchellbosecke/benchmark/Pebble.java

**Comment by ebussieres** [comment]
Just added pebble-performance-test project in organization 

https://github.com/PebbleTemplates/pebble-performance-test
