### ISSUE TITLE
Consider using and extending AbstractViewResolverProperties for spring boot integration

### ISSUE THREAD

**Issue by okohub** [PebbleTemplates/pebble#369]
Hello,

Thank you for this great project, I want to suggest something about PebbleProperties; 

Most of view integrations in spring boot uses AbstractViewResolverProperties for base property support in order to configure views very easily. Also Lots of existing properties are already defined here. 

Can we make a shot for it?

**Comment by ebussieres** [comment]
Yeah sounds good to me

**Comment by okohub** [comment]
@ebussieres PR's welcome? :)

**Comment by ebussieres** [comment]
Sure

**Comment by okohub** [comment]
thank you very much @ebussieres
