### ISSUE TITLE
Presizing Lists/Maps on creation

### ISSUE THREAD

**Issue by hc-codersatlas** [PebbleTemplates/pebble#370]
There are many places, e.g. in CoreExtension where Collections are initialized without a default size. A minor optimization would be to put in some default sizing values based on the items added in the code. In most cases where users don't customize these - the sizes will likely be correct and not resize again to create garbage.

**Comment by ebussieres** [comment]
CoreExtension is instanciated only one when building pebbleengine. I don't think it really affect performance here.

**Comment by hc-codersatlas** [comment]
That was just an example. It also occurs in every filter, test, etc...

**Comment by ebussieres** [comment]
I don't consider this an issue so i'll close it. You can make a pull request to address this if you want
