### ISSUE TITLE
Accessing EvaluationContext in template

### ISSUE THREAD

**Issue by okohub** [PebbleTemplates/pebble#372]
Hi,

It can be handy to access EvaluationContext in template, sometimes we need to access locale object but instead of accessing locale, EvaluationContext will be better.

**Comment by ebussieres** [comment]
If you need to access EvaluationContext, you need to write a custom function/filter

**Comment by okohub** [comment]
@ebussieres oops, look like both locale and context are already added to scope! :)

com/mitchellbosecke/pebble/template/PebbleTemplateImpl.java:166

```
 locale = locale == null ? this.engine.getDefaultLocale() : locale;

    // globals
    Map<String, Object> globals = new HashMap<>();
    globals.put("locale", locale);
    globals.put("template", this);
```
