### ISSUE TITLE
Set result of include or macro operation evaluation to a variable

### ISSUE THREAD

**Issue by okohub** [PebbleTemplates/pebble#373]
Hello,

Is there a way to add result of macro or template inclusion result to a variable? Thus, we can use same rendered html in template many times.

**Comment by ebussieres** [comment]
No I don't think it's supported. Do you have a example of what you'd like to achieve ?

**Comment by ebussieres** [comment]
Yes ... or you can include a template two times. You should define a model object which gonna contain a pagination object.

**Comment by okohub** [comment]
It can be a pretty good feature, users can gain some performance boost with this, I think.
