### ISSUE TITLE
Using Pebble to render HTML Emails in Spring Boot 2 

### ISSUE THREAD

**Issue by met68** [PebbleTemplates/pebble#374]
I have a Spring Boot 2 MVC-type web application and which uses Pebble as a template engine. I am a bit of a Java noob, but so far, all works well.

However, I am now trying to also render HTML emails in this application, using Pebble also.

For instance, I am trying to autowire the PebbleEngine pebbleEngine in the user registration controller and passing it to a Template class I created which contains the following function:

`public String render(PebbleEngine pebbleEngine) throws Exception {`
  `PebbleTemplate template = pebbleEngine.getTemplate(this.view);`
  `template.evaluate(Template.writer, this.model, this.locale);`
  `return writer.toString();`
`}`

I am using a newly instantiated StringWriter in the Template class for writer. Model, Locale and View are also properties of the Template class.

This almost works, BUT, for some reason, the content of my HTML registration emails (which use inheritance, i.e. a register.pebble template which extends an emailBase.pebble template) always get rendered twice.....

I also tried to autowire the PebbleEngine pebbleEngine inside the Template class, but this never works.

How do we (best) use Pebble to correctly render emails in a Spring Boot 2 web application which already uses Pebble as a template engine?

**Comment by ebussieres** [comment]
It doesn't seem to be related to pebble but related to the way you use spring mvc. Can help you much here without a working example of your controller. The value you return in a controller should be the template and you should just fill the model. 

Please take a look at https://github.com/PebbleTemplates/pebble-example-spring

**Comment by met68** [comment]
Apologies, I should have clarified, but I am using the following dependency:

`<dependency>`
  `<groupId>io.pebbletemplates</groupId>`
  `<artifactId>pebble-spring-boot-2-starter</artifactId>`
  `<version>3.0.0</version>`
`</dependency>`

The relevant parts of the  controller simply do the following (attributes is the model HashMap):

...

`@Autowired`
`PebbleEngine pebbleEngine;`

...

`Template template = new Template("email/registration", attributes, locale);`
`try {`
  `content = template.render(pebbleEngine);`
`} catch (Exception e) {`
  `e.printStackTrace();`
`}`
...

The relevant parts of the Template pojo class look like this:

...

`private static Writer writer = new StringWriter();`

...

`public String render(PebbleEngine engine) throws Exception {`
  `PebbleTemplate template = engine.getTemplate(this.view);`
  `template.evaluate(Template.writer, this.model, this.locale);`
  `return Template.writer.toString();`
`}`

...

**Comment by ebussieres** [comment]
Please provide a working sample if you want some help. I don't have enough information to help you or to determine if it's really a bug.

**Comment by ebussieres** [comment]
Wow... If you want some help, i suggest that you submit a test case or a link to a github project to demonstrate you're setup. I already answered that you'll probably need to setup a second PebbleEngine to render html. I have already used pebble in a project that was used to render html and render email and I used 2 PebbleEngine. Maybe we can add a guide on the wiki.

https://github.com/PebbleTemplates/pebble-spring-boot-starter has been merged with the pebble repository(https://github.com/PebbleTemplates/pebble/tree/master/pebble-spring). That's why it has been archived and it still activily suppoorted.

Documentation on  http://mitchellbosecke.com/pebble/home is no longer up to date. Mitchell has quit the project and didn't remove the documentation. Can't do much here. The official documentation is on the wiki(https://github.com/PebbleTemplates/pebble/wiki/documentation) like said in the README of the pebble project.

**Comment by met68** [comment]
Thanks for the quick reply and the clarification re the spring-boot-starter project. As I said, I am a bit of a Java (and especially Spring) noob, so when you casually say I have to setup a second engine to render html emails, that, unfortunately, means exactly nothing to me. Obviously, that is my problem, but yes, I think an example somewhere would be very helpful, at least for me (and I am sure there are others who may appreciate it). The project you mention where you used 2 engines, is that a Spring Boot project and if so, where can one find it?

In my setup above, I have tried to instantiate a new engine in my Template class like so:

`private static PebbleEngine engine = new PebbleEngine.Builder().build(); `

instead of passing it into my render() function in my Template class, but that did not work and it also does not find my templates anymore.

**Comment by ebussieres** [comment]
Just added an example here that reuse the same PebbleEngine:

https://github.com/PebbleTemplates/pebble-example-spring/tree/master/spring-boot-with-email

**Comment by met68** [comment]
Thanks for this, but I don't think that's what I am looking for and I am not sure, whether you actually tried to send an html email with this. In principle, what you are doing in this example I don't think is too dissimilar from what I am doing and yes, as I said in my original post, I always got my webapp to render and send the html email, BUT, the html content is always being rendered TWICE.

When you google for sending html emails with Spring Boot, there are many complete and well documented articles/ examples around for Thymeleaf, Velocity etc., alas, none for Pebble. 

I have now literally wasted days with this (luckily I am just working on a personal little project), but it has taken me less time to write the entire application, than it has to try and figure-out this little thing and as I said, this is not the first time, that I have wasted hours/ days when working with Pebble. 

So, while I will certainly continue to use Twig when working with PHP, I think I will need to simply find an other template engine for Java.

But I wish you guys all the best of luck!

**Comment by ebussieres** [comment]
You should change your attitude if you want help from others. I'm 100% sure it's a problem with your setup. Don't know why you're using a Template object but like you said, you're a java/spring noob and you'll certainly need a lot of practice.

I also wasted my time trying to help you and wish you best of luck ...
