### ISSUE TITLE
Updating the elements of a Map, using "Set"

### ISSUE THREAD

**Issue by electrotype** [PebbleTemplates/pebble#377]
I have a `for` loop _which may contains duplicate elements_. I want to be able to skip elements that were already outputed.

What I tried :

```
 {% set elementsDone = {} %}
 {% for element in myElements %}
     {% if elementsDone[element.id] is empty %}
         {% set elementsDone[element.id] = true %}
         // Display element!
     {% endif %}
{% endfor %} 
```

But it seems the `set` directive can't update a `Map` : "_Unexpected token of value "[" and type PUNCTUATION_".

What do you suggest to keep track of elements already managed, inside a loop?

**Comment by electrotype** [comment]
I did find a workaround using a string and `contains`, but it's obviously very ugly :

```
 {% set elementsDone = '' %}
 {% for element in myElements %}
    {% if not (elementsDone contains '|' + element.id + '|') %}
        {% set elementsDone = elementsDone + '|' + element.id + '|' %}
         // Display element!
     {% endif %}
{% endfor %} 
```

**Comment by cjbrooks12** [comment]
You can call the methods on the Map object itself, even if the `set` tag doesn't have syntax for it directly.

```jijna
{% set elementsDone = {} %}
 {% for element in myElements %}
     {% if elementsDone[element.id] is empty %}
         {{ elementsDone.put(element.id, true) }}
         {{ element.title }}
     {% endif %}
{% endfor %}
```

**Comment by electrotype** [comment]
Works well, thanks!
