### ISSUE TITLE
Component based html page   (question)

### ISSUE THREAD

**Issue by colesico** [PebbleTemplates/pebble#378]
I plan to create pages based on reusable, nested components.
For example, a simple button component I can define with the macro (as mentioned in the documentation):

```
{% macro button (label)%}
<input type = "button" value = "{{label}}" />
{% endmacro%}

```
And somewhere on the page I can specify two buttons:

`{{button ("Ok")}}  <br/> {{button ("Cancel")}}`

It is clear how to do this.

But what about  complex component, where the parameters values must be not just text strings  but whole blocks of code, for example:

I made the "Dialog" component that has a "header" and a "body" parts:

```
{% macro dialog (header, body)%}
	<div>
		<div id = "header"> {{header}} </ div>
		<div id = "body"> {{body}} </ div>
	</ div>
{% endmacro%}
```

And somewhere on the page I use it twice:  

for the first use:

` {{dialog ("My header", body ="My body")}}   `

and for the second use, the value of the "body" parameter must be not just string but the code block:

```
  <div>
     {{button ("Ok")}}  <br/> {{button ("Cancel")}}
  </ div>
```
  
Also page can contains not just one component like the "Dialog" but multiple different components with  blocks of code as the parameters values

Thnx!

**Comment by cjbrooks12** [comment]
To use a macro, it must be defined in the same template, or else [imported](https://github.com/PebbleTemplates/pebble/wiki/import) from another template.

Currently it is not possible to pass an HTML block to a macro, but there has been talk of adding an `embed` tag (#319) that would allow similar functionality.

**Comment by cjbrooks12** [comment]
Include statements are evaluated dynamically, so one solution would be to pass a string to your macro, where that string defines a template name to include. Not ideal, but it would certainly allow for this kind of reuse.

```jijna
{% macro dialog(header, body, vars) %}
<div>
<div id="header">{% include header with {"vars": vars} %}</div>
<div id="body">{% include body with {"vars": vars} %}</div>
</div>
{% endmacro%}

{{ dialog('includes/dialog/header.peb', 'includes/dialog/body.peb', {"title": "My Title"}) }}
```
