### ISSUE TITLE
Update http://pebbletemplates.io or take it offline

### ISSUE THREAD

**Issue by ChristianCiach** [PebbleTemplates/pebble#379]
The official website still lists 2.4.0 as the current version and contains outdated documentation.

Seeing that the github wiki contains a better documentation anyway, I propose to take the website offline to avoid confusion and improve discoverability of the proper documentation (this github page).

**Comment by ChristianCiach** [comment]
As an alternative, if you don't have administrative access to the website, you should at least edit the URL inside pebble/pom.xml. I was confused, because the link over at maven central still points to the old website.

**Comment by ebussieres** [comment]
@hectorlf Can you redirect  http://pebbletemplates.io to the github wiki instead of the old page of Mitchell ?

**Comment by hectorlf** [comment]
Done.
