### ISSUE TITLE
Consider to use "unbescape" instead of "Coverity Escapers"

### ISSUE THREAD

**Issue by ChristianCiach** [PebbleTemplates/pebble#380]
Coverity Escapers is extremely outdated and may or may not work correctly for current markup languages.

Unbescape is actively maintained and is used by other active template engines.

I may submit a pull request for this, but I wanted to draw attention to this first.

**Comment by ebussieres** [comment]
@ChristianCiach Sure just submit a PR for this

**Comment by ebussieres** [comment]
@ChristianCiach Gonna be available in next release

**Comment by ChristianCiach** [comment]
You really are fast! I planned to do that tomorrow :) Looks like it was even easier than I anticipated.

**Comment by ebussieres** [comment]
@ChristianCiach Release done ... gonna be available in maven central soon
