### ISSUE TITLE
Investigate if Caffeine cache is really necessary

### ISSUE THREAD

**Issue by ChristianCiach** [PebbleTemplates/pebble#381]
I think libraries like this should have as few dependencies as possible. When used in a large project (as ours) this easily leads to version clashes with other libraries.

Looking at the code, Caffeine is used in a very simple way and the usage of this library seems a bit overkill. Seeing that pebble depends on Java 8 since version 3.0.0, a ConcurrentHashMap (which can be used as a loading cache using the new lambda-compatible methods) should be more than adequate.

I may submit a pull request for this.

**Comment by decebals** [comment]
Maybe an interface with a default implementation (no external dependencies) and an optional (in pom.xml) Caffeine based implementation.

**Comment by ebussieres** [comment]
Like the idea of @decebals to have an interface. We can provide a default implementation using ConcurrentHashMap. I'd like to give the option of another another cache implementation to the enduser (if you want cache with TTL for example)

**Comment by ebussieres** [comment]
Gonna be available in next release
