### ISSUE TITLE
Bug ? ParserException: Unexpected tag name "endfor"

### ISSUE THREAD

**Issue by mmaryo** [PebbleTemplates/pebble#382]
Hello
I have this error when I put {% endfor %} tag 

`com.mitchellbosecke.pebble.error.ParserException: Unexpected tag name "endfor" (home:820)`

My stack is : 

Spring Boot 2.0.4
Java 10
pebble-spring-boot-2-starter

And the html is : 

`{% for moment in moments %}      
....      
{% endfor %}`

Is it a bug ?

**Comment by ebussieres** [comment]
Sounds like a problem with your template. Can you provide the content of all your template ?

**Comment by mmaryo** [comment]
I forgot an {% endif %} before the endfor ... :/
thank to you
