### ISSUE TITLE
Calling Java methods that expect a String using a different type?

### ISSUE THREAD

**Issue by mtdowling** [PebbleTemplates/pebble#386]
Say I have a template like this:

```
{% set variable = true %}
{{ Foo.bar(variable) }}
```

And the `bar` method of the `Foo` variable is, say:

```java
String bar(String value) {
    return value;
}
```

This fails to call the method correctly because the method requires a String parameter but was given a boolean.

Would it be possible to automatically call `String.valueOf` on properties that expect a string *or* would it be possible to add a built-in `toString` filter?

Then I could do:

```
{% set variable = true %}
{{ Foo.bar(variable | toString) }}
```

**Comment by ebussieres** [comment]
I don't think it should be in pebble core. You should define your own filter to do something like that.

**Comment by mtdowling** [comment]
Sure. I suppose I can just call `toString()` on values too since they're all boxed.

**Comment by jochen777** [comment]
Another solution is to create a new method on your class, that accepts a boolean. So in your example:

`public String foo(boolean bar) {
    return String.valueOf(bar);
  }`
