### ISSUE TITLE
Any plans to support Java 9 modules (Jigsaw)?

### ISSUE THREAD

**Issue by mtdowling** [PebbleTemplates/pebble#391]
Are there any plans for this project to support Java 9 modules?

**Comment by ebussieres** [comment]
We've just moved to java 8 as minimum requirement so no, not in the short term. 

What's your need with java 9 modules ?

**Comment by mtdowling** [comment]
Adding support for modules allows people to use Pebble with tools like [jlink](https://docs.oracle.com/javase/9/tools/jlink.htm) that can create a standalone executable that contains only the classes and parts of the JRE that are used in their application.

To support it in a way that doesn't require Java 9 but still supports modules is an interesting question. I know that Jackson, Guava, and other popular projects are trying to to figure this out too.

**Comment by colesico** [comment]
add at least an java9 Automatic-Module-Name  to manifest

**Comment by ebussieres** [comment]
@colesico Never tried java9 module. You can submit a PR to add that to the manifest if you need it

**Comment by zimmi** [comment]
I opened https://github.com/PebbleTemplates/pebble/pull/416 to add automatic module names. Please feel free to comment, since the module name is supposed to be permanent.

**Comment by zimmi** [comment]
@ebussieres Sorry for nagging, but can you take a look at PR https://github.com/PebbleTemplates/pebble/pull/416? An official, stable module name would greatly help those projects using pebble on the module path, right now they have to make up a name or use the generated one, which will likely break in the future.
