### ISSUE TITLE
Add JSON escaping

### ISSUE THREAD

**Issue by stevespringett** [PebbleTemplates/pebble#395]
The majority of my templates are JSON. It would be nice to have JSON escaping as part of the default escaping strategies. It's included in unbescape.

**Comment by ebussieres** [comment]
Sure sounds good to me

**Comment by ebussieres** [comment]
You can try it with 3.0.4-SNAPSHOT. See https://github.com/PebbleTemplates/pebble/wiki/installation to set up your project with SNAPSHOT.

I'm gonna create the release in 1-2 weeks
