### ISSUE TITLE
Overzealous Expression Check

### ISSUE THREAD

**Issue by jasefws** [PebbleTemplates/pebble#398]
The following engine settings
```
PebbleEngine engine = new PebbleEngine
        .Builder()
        .loader(new StringLoader())
        .strictVariables(true)
        .autoEscaping(false)
        .build();
```

with the template
```
{%- set a = null -%}

{{- a is not null and a.toLowerCase() == "abc" -}}
{#- or -#}
{%- if a is not null and a.toLowerCase() == "abc" -%}
        Do something
{%- endif -%}
```

would work in 2.4.0, but no longer works in 3.0.3.

**Comment by ebussieres** [comment]
StrictVariable set to true is causing the problem. See https://github.com/PebbleTemplates/pebble/issues/245

**Comment by ebussieres** [comment]
That changes was made by Sam Lanning. Here's the comment 

Add tests for handling null values in bool logic  Add tests for how we would expect boolean logic to work in both strict mode and non-strict mode regarding null values (for not(), and and or), given that currently null is implicitly used as false in an if block, but nowhere else.  In strict mode, null values (not just null variables) are forbidden everywhere.

It seems a bit weird to me.

**Comment by jasefws** [comment]
Thanks for the code change. Works like a charm!
I expect the logic expression to be behaving like any typical language, as would our customers who write their own templates within our product.

We use strict mode to allow validating the template's output on the fly with the domain objects supplied to it for users to quickly test for any bad/unusual behaviours, and to design the template by using the correct variables and their attributes.
Without it, you can mention any variable or attribute and it can have unpredictable results.

And on the topic about the strict mode having nulls as forbidden everywhere, I personally have not had any issue with nulls in 2.4.0. Might be due to making sure to test for them, but any errors caused by nulls for us is then a badly designed template.

**Comment by ebussieres** [comment]
Will be fixed in next release
