### ISSUE TITLE
Call macro by reference like java lambda

### ISSUE THREAD

**Issue by colesico** [PebbleTemplates/pebble#401]
Can I call one macro from another when the first is passed to the second as a "reference" in the parameters  (like java 8 lambda)?

For example:

```
{% macro embeddable(text) %} <div>{{  text }}</div> {% endmacro %}

{% macro wrapper(embRef,text) %}
   <div>
    {{ embRef(text) }}
   </div>
{% endmacro %}

Call:
 {{ wrapper(embeddable,'Hello') }}
```

I'm trying to use a component approach for pages constructing. But pebble does not allow to do this conveniently. No possibility to pass code blocks to a macro or use embed tag like twig.

**Comment by ebussieres** [comment]
You can't pass a macro as a reference. There's already an issue for an embed tag (#319). I'll close this one as a duplicate and you're welcome to submit a PR for the embed tag if you need one.
