### ISSUE TITLE
Passing the writer instance to sub templates (question)

### ISSUE THREAD

**Issue by danielstieger** [PebbleTemplates/pebble#407]
Gentlemen,

i didn't find a place to post a question, so it ended up as this issue. I beg for excuse if this is the wrong place ... 

I m just wondering how one can/should render sub-templates with pebble. With the django template engine, this is quite straightforward, since strings are return when evaluating a template against a context. In Pebble, the result is rendered to a writer instance. 

In django i could do
```
{% for delegate in form.delegate %}
{{ delegate.toHtml }}
{% endfor %}
```
Each delegate (and editor) in a form is quite complicated and comes with its own local context map. Since they are so different, only the delegate itself knows variables available in that context. Thus, the toHtml() method just uses a locally, already complied template and puts its rendered content into some outer form template. 

Now of course i could implement the toHtml() method for pebble as 
```java
String toHtml() {
StringWriter writer = new StringWriter();
.... context = ;

precompiledPebbleTemplate.evalute(writer, context);
return writer.toString()
}
```
However, i have to instantiate that StringWriter to get some String content back.. 

Is there an more obvious way to handle such a scenario? Or should i pass in the Http Writer to each delegate when instantiating in a form that i do addToWriter() instead of toHtml()

```java
void addToWriter() {
.... context = ;

precompiledPebbleTemplate.evalute(global_http_writer_instance, context);
}
```

Or, alternatively, is there a way to come up with a ` void toHtlm(Writer writer) { ... }`, but then, i would need to pass over the writer somehow ..

Cheers, any suggestion appreaciated,
Daniel

**Comment by cjbrooks12** [comment]
Does the [include](https://github.com/PebbleTemplates/pebble/wiki/include) tag not cut it here? Templates are included dynamically, so you can pick the template to render based on the delegate, and you can also pass additional values to that template when it is rendered. 

```jinja
{% for delegate in form.delegate %}
{% include delegate.template with {"data": delegate.data} %}
{% endfor %}
```

**Comment by danielstieger** [comment]
Indeed sir,

this is a compelling solution. It s possible to include "dynamically" by referencing vars, as well as creating context by vars . Nice, didn t realize that! 

Thanks a lot!!!
