### ISSUE TITLE
(question) when rendering failed, is there any way to know what's wrong?

### ISSUE THREAD

**Issue by hooni24** [PebbleTemplates/pebble#413]
I've got an error log like this

```
 o.s.boot.web.support.ErrorPageFilter     : Cannot forward to error page for request [/blog/board/view] as the response has already been committed. As a result, the response may have the wrong status code. If your application is running on WebSphere Application Server you may be able to resolve this problem by setting com.ibm.ws.webcontainer.invokeFlushAfterService to false

com.mitchellbosecke.pebble.error.PebbleException: Could not perform addition (blog/board/boardView:148)
```

but I couldn't find out what's going wrong.
I have pebble file in ```/blog/board``` directory with ```boardView.peb```
and my spring controller has ```@RequestMapping("/blog/board/view")``` method.. with return ```boardView``` (ofcourse, configurated prefix and postfix)

so, i expect when ```/blog/board/view ``` request is comming,
then render ```blog/board/boardView.peb``` file.
but it doesn't work

how can i handle it ? please let me know

**Comment by ebussieres** [comment]
I assume that you're using spring-boot ?

I really don't think it's an issue with pebble. Can you paste the content of your @RequestMapping("/blog/board/view") method ?

**Comment by hooni24** [comment]
@ebussieres  
thanks for your attention.
You're right. I figured out it wasn't issue with pebble.
It was just spring-boot error configuration fault by me.
please just forget about it. and I'm so sorry for this foolish question to you.
I think this is should be closed.

before close, can i ask you just 1 more maybe simple thing?
I learned default error page of spring-boot is
```classpath:/error.jsp```
but, now I'm using pebble, then is it change automatically error page for
```classpath:/error.peb?```

I know it isn't related with pebble project, but I wish you answer this question please.

**Comment by ebussieres** [comment]
No it's not. You need to configure it.

Please refer to https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/web/servlet/error/ErrorMvcAutoConfiguration.java or spring boot guide
