### ISSUE TITLE
Global variables lazy load support

### ISSUE THREAD

**Issue by CodePlayer** [PebbleTemplates/pebble#415]
I'm a new pebble user. I want to inject some global variables in pebble context. 
However, getting some variables is a relatively expensive operation.
I hope to get it when I really need it. It means that the pebble could increase support for lazy loading.
For example, if a variable implements a java interface named `java.util.function.Supplier`, pebbel should invoke it's `get()` method to get the actual value.

**Comment by ebussieres** [comment]
Should be easy to add Supplier support. I'll take a look

**Comment by jochen777** [comment]
Why don't you implement this on your own? (Deliver the expensive variables as objects with a "get" method, that will fetch the result only on demand)
Pebble will become slower with that by checking each variable with "instanceof".... And we all love pebble for its speed :)

**Comment by ebussieres** [comment]
Take a look [here](https://pebbletemplates.io/wiki/guide/extending-pebble/) in last section (Attribute resolver (v3 only)).

I suggest first that you add your custom attribute resolver in the chain for Supplier support and it should work.

**Comment by ebussieres** [comment]
@CodePlayer Did you try to define a custom attribute resolver ?

**Comment by CodePlayer** [comment]
@ebussieres Yes, I've already done this.

**Comment by CodePlayer** [comment]
OK, it works! I will close this issue later. Many thanks!
