### ISSUE TITLE
Instanceof Operator Support

### ISSUE THREAD

**Issue by msnijder30** [PebbleTemplates/pebble#418]
### Origin of question
Recently I came across [this issue](https://stackoverflow.com/q/53846761/4417306) on Stackoverflow, which asked if something like an `instanceof` operator existed in Pebble (which, as far I can see, does not exist).

### My solution
I came up with the [following answer](https://stackoverflow.com/a/53866019/4417306), which adds `instanceof` as new operator.

---

I wrote  `InstanceExpression.java` which evaluates a format like `myvariable instanceof "java.lang.String"`, and checks if `myvariable` is actually an instance of `String`.
<details><summary>InstanceofExpression.java</summary>
<p>

```java
public class InstanceofExpression extends BinaryExpression<Object> {

	@Override
	public Object evaluate(PebbleTemplateImpl self, EvaluationContextImpl context) {
		// The left class (left instanceof right)
		Object leftClass = getLeftExpression().evaluate(self, context);

		// The right class, this is a string with the full qualifying name of
		// the class eg (left instanceof "java.lang.String")
		String rightClassname = getRightExpression().evaluate(self, context).toString();

		// We must get the right class as Class<?> in order to check if left is
		// an instanceof right
		try {
			Class<?> rightClass = Class.forName(rightClassname);

			// Check if the left class is an instanceof the right class
			return rightClass.isInstance(leftClass);
		} catch (ClassNotFoundException ex) {
			throw new PebbleException(ex,
					String.format("Cannot find class %s", rightClassname), this.getLineNumber(), self.getName());
		}
	}

}
```
</p>
</details>
</br>

And then ofcourse `InstanceofExtension.java` which adds the `instanceof` operator, with a precendence of 30 since that's also the value Pebble uses for `< > <= >=` which is on the same level as `instanceof` as seen in [Java 8 - Operators](https://docs.oracle.com/javase/tutorial/java/nutsandbolts/operators.html).

<details><summary>InstanceofExtension.java</summary>
<p>

```java
public class InstanceofExtension implements Extension {

	public List<AttributeResolver> getAttributeResolver() {
		return null;
	}

	public List<BinaryOperator> getBinaryOperators() {
		return Arrays.asList(new BinaryOperatorImpl("instanceof", 30, InstanceofExpression.class,
				Associativity.LEFT));
	}

	public Map<String, Filter> getFilters() {
		return null;
	}

	public Map<String, Function> getFunctions() {
		return null;
	}

	public Map<String, Object> getGlobalVariables() {
		return null;
	}

	public List<NodeVisitorFactory> getNodeVisitors() {
		return null;
	}

	public Map<String, Test> getTests() {
		return null;
	}

	public List<TokenParser> getTokenParsers() {
		return null;
	}

	public List<UnaryOperator> getUnaryOperators() {
		return null;
	}

}
```

</p>
</details>
</br>

And then using it like this:
```java
PebbleEngine engine = new PebbleEngine.Builder()
			.strictVariables(true)
			.extension(new InstanceofExtension())
			.build();
```

### Question(s)

- Is there a reason this is not included in pebble? (eg this is not what pebble is supposed to do / performance / this conflicts with something / other)
- Would this be a good feature/should I create a pull request after implementing it?

**Comment by ebussieres** [comment]
Using instanceof in a template is wrong from an architectual standpoint. If you find yourself in a position where you "need" it, you have probably uncovered a problem in your architecture. 

So that's why it's not in Pebble core. Twig doesn't have this operator too.

What's your use case for that operator ?

**Comment by msnijder30** [comment]
I wasn't aware that it was something that shouldn't appear in a template. After some research online many people agree with your standpoint so I guess it's not something that should be included.

The use case was Pebble with `strictVariables` on and checking if an object is a specific type, before calling a certain method/parameter of it. The use case came from that question on StackOverflow (not myself) so I don't have a real example except this explanation.

I guess if anyone does find themselves in the situation where they need it, they can refer to the code in this issue 👍

**Comment by robshep** [comment]
> Using instanceof in a template is wrong from an architectual standpoint. If you find yourself in a position where you "need" it, you have probably uncovered a problem in your architecture.

I'd like to use this pattern.  I have a map of objects, some polymorphic, some not, some are primitives. This would be a quick way of showing a templated component for each.  

It's a shame this is mechanism is not included, when it is a basic operator in the underlying language. 

R
