### ISSUE TITLE
Spring boot 2 not working with custom loader

### ISSUE THREAD

**Issue by martijnhiemstra** [PebbleTemplates/pebble#420]
I have a spring boot 2 project and I have included pebble. I start by creating a custom file loader to override the default classpath loader. 

This is my spring bean:

```
@Configuration
public class PebbleFileLoader {

	@Value("${email.template.prefix:''}")
	private String emailTemplatePrefix;

	@Bean
	public Loader<?> pebbleLoader() {
		if (this.emailTemplatePrefix == null || this.emailTemplatePrefix.isEmpty()) {
			return new ClasspathLoader();
		} else {
			FileLoader fileLoader = new FileLoader();
			fileLoader.setPrefix(this.emailTemplatePrefix);
			fileLoader.setSuffix(".html");
			return fileLoader;
		}
	}

}
```
The reason for this setup has to do with testing. During testing no prefix is set and we must test relative where as in develop or production we must use a absolute path. 

Since the fileloader is not working I decided to debug the application. I found that PebbleAutoConfiguration does pickup my fileloader with the custom prefix. However when I generate a template using the following code:

```
PebbleTemplate pebbleTemplate = pebbleEngine.getTemplate(templateName);
pebbleTemplate.evaluate(writer, parameters);
```

when I debug I can see that pebble has switched back to the default fileloader (The pebble prefix is back to /template/ and not the valu set. )

Theer is something really wierd going on. Why does the right fileloader get picked by the auto configure and the engine use a different fileloader???

**Comment by ebussieres** [comment]
Can you provide a simple working sample or a test case ?

**Comment by martijnhiemstra** [comment]
https://github.com/PebbleTemplates/pebble

TemplateDIrectory = Where the templates are located.

This is a demo project. I created it in Spring Tool suite 4 although it should work in any IDE. I can see that FileLoader in PebbleFileLoader.java is picked up by Spring and that the fileloader is created. I can see that the prefix is set to TemplateDIrectory. 

Then call http://localhost:8080/template/demo and debug the FileLoader class. You will see that the prefix is back to the default value ("/template") and that the fileloader isnt finding the templates.

**Comment by ebussieres** [comment]
@martijnhiemstra I think I found the problem. You need to define the prefix and suffix in the PebbleViewResolver too.

Please add the following properties in your application.properties:

pebble.prefix=xxx
pebble.suffix=xxx

If you carefully check the PebbleAutoConfiguration class, you'll see that the Loader and the ViewResolver use the same prefix and suffix from PebbleProperties.
