### ISSUE TITLE
Is there any split function?

### ISSUE THREAD

**Issue by pun-ky** [PebbleTemplates/pebble#421]
my case, value to be consumed `{ links: "http://my-product.com/images/1.jpg|http://my-product.com/images/2.jpg|http://my-product.com/images/3.jpg" }`

```
{% for item in response.items %}
{% set links = split(item.links, '|') %}

{% for link in links %}
  <a href="{{{link}}}">{{{link}}}
```

yep it is trivial but I have no easy way to manipulate `response.items` (change pojo of item in collection, because of complex stack of my application, I can only apply changes on tpl engine level).
only implementing it by my own is a way to go? how about introducing it to Pebble?

I see `join` https://pebbletemplates.io/wiki/filter/join/ but complementary function `split` ... there is no such method, right? especially if we have `set` this makes sense (yep it will increase logic / complexity of tpl which is not desired, but this is an edge case ;)

**Comment by ebussieres** [comment]
Yes I also think it should be added in pebble. Would you like to create a pull request for this ?

**Comment by ebussieres** [comment]
It's gonna be available in next release

**Comment by pun-ky** [comment]
thank you! greetings
