### ISSUE TITLE
Access to variables from macro (again)

### ISSUE THREAD

**Issue by setevoy** [PebbleTemplates/pebble#425]
Seems like related issue.
I use template block "info" to store some metadata (yaml) inside template. I evaluate it during site load, outside of any HTTP request. 
For some reason when I'm evaluating info block, rest of template is evaluated also (BTW why?). So I setting "loading" flag to indicate, it's not regular request. I wrote extension functions and they use "loading" flag to return reasonable defaults instead of trying to access HTTP request.
It worked until I called one of such functions from macro. Now function doesn't see my flag. Here is test case:

```Java
    @Test
    public void noAccessToContextFromMacro() throws PebbleException, IOException {
        PebbleEngine pebble = new PebbleEngine.Builder().loader(new StringLoader())
                .extension(new AbstractExtension() {
                    @Override
                    public Map<String, Function> getFunctions() {
                        return Collections.singletonMap("func", new Function() {
                            @Override
                            public Object execute(Map<String, Object> args, PebbleTemplate self, EvaluationContext context, int lineNumber) {
                                if (context.getVariable("loading") != null) return null;
                                throw new IllegalStateException("NO HTTP REQUEST!");
                            }

                            @Override
                            public List<String> getArgumentNames() {
                                return Collections.EMPTY_LIST;
                            }
                        });
                    }
                })
                .strictVariables(false).build();
        String templateContent = "{% block info %}someinfo{% endblock %}{{ test(_context) }}{% macro test(_context) %}{{ func() }}{% endmacro %}";
        PebbleTemplate template = pebble.getTemplate(templateContent);

        Writer writer = new StringWriter();
        template.evaluateBlock("info", writer, Collections.singletonMap("loading", true));

        assertEquals("someinfo", writer.toString());
    }

```

I'm not sure, but seems like && should be instead of || here: https://github.com/PebbleTemplates/pebble/blob/5f8d9ccc3639f7872c8c0df7505491e1aa5f5575/pebble/src/main/java/com/mitchellbosecke/pebble/template/ScopeChain.java#L133

_Originally posted by @setevoy in https://github.com/PebbleTemplates/pebble/issues/231#issuecomment-457923450_

**Comment by ebussieres** [comment]
Since the function is called within a macro and you want to access global attributes, you should use this code instead

```
@Override
              public Object execute(Map<String, Object> args, PebbleTemplate self, EvaluationContext context, int lineNumber) {
                if (context.getVariable("_context") != null) {
                  GlobalContext globalContext = (GlobalContext) context.getVariable("_context");
                  if (globalContext.get("loading") != null) {
                    return "someinfo";
                  }
                }
                throw new IllegalStateException("NO HTTP REQUEST!");
              }
```

**Comment by setevoy** [comment]
I ended with exactly this solution, but thought it was a hack )

Pebble is nice and intuitive. I even added several custom tags easily just by example.

But not macro. 
With Java background I waited that the variable is resolved from the bottom scope and up till global variables. Presense of ScopeChain class reinforced this expectation. But then I came to some repeated html in template, tried to encapsulate them using macro and problems began.
I needed to pass _context to macro every time. Inexplicable, but ok, but still doesn't help accessing variable from custom function, as I described above.

I diged code a little and came to the concept of "local" Scope. We have to jump over it passing _context to the macro and casting _context to GlobalContext. The "local" Scope used in single place - macro. But why? What's the idea behind "local" scope? Where is it useful?

**Comment by ebussieres** [comment]
localScope in scopeChain should be renamed to macroScope. It is exclusively used for macro.

By definition, a macro doesn't have access to any variable outside his scope. We introduced the _context variable to access global variables, just like Twig do. _context variable was introduced in https://github.com/PebbleTemplates/pebble/issues/242, you can take a look. See https://github.com/PebbleTemplates/pebble/issues/371 too.

**Comment by setevoy** [comment]
So reasons are:

**Twig does so**
And it [explains](https://twig.symfony.com/doc/2.x/tags/macro.html) why: 
> But as with PHP functions, macros don't have access to the current template variables.

But Java functions _do_ have access to global variables. Unless there is intention to port ready twig templates to pebble as is.

**To hide information** 
From whom? After all template is intended to present information, not to hide it.

I totally agree with @mbosecke comment https://github.com/PebbleTemplates/pebble/issues/242#issuecomment-297070600

> I also like that macros used to provide "information hiding" but in my experience this caused more harm than good. It wasn't flexible enough for my use cases. Perhaps using a special variable name is the appropriate middle ground but I've never been a fan of special variables; they always feel like a work-around to a problem but maybe that's just me.

From #371 I see, that _local variable_ was needed, but whole _local scope_ implemented instead.

Locality is great, but on variable level. 
Why not to take good things from Java?
Need global variable? Just access it. No magic _context.
Need local variable? Declare it. Variable will be local in last scope. It will hide global variable with the same name if any.
Noty only {% macro %} deserves local varables. Other tags will also benefit from it.
Declare scope implicitly if needed. Twig has {% with %}.

Scope already allows Lazy varaibles. All variables can be wrapped in some Variable wrapper. It can be lazy. It can be local. It definitely answers: is variable missing in current scope, or it is null with single lookup.

Just thoughts.

**Comment by okohub** [comment]
> Need global variable? Just access it. No magic _context.

@setevoy I think this is not developer friendly. Instead, the real magic is accessing a variable which is not even defined or introduced in macro. Also, with "_context" approach, you can check each global variable by searching starts with "_context". It is readable and refactorable.

The thing is, this design decision is not about Java or another language. IMHO, We should just follow readable and developer friendly code principals.

**Comment by setevoy** [comment]
I use a macro to collapse four-lines stacked divs bolerplate into a pretty short one-liner. 
Kind of c #define style macro.

If we want to really "hide" upper context, passing _context is still hackish way to access variables not introduced in this context. Instead, we should pass every variable, macro might use, as a parameter.

```
{{ productInfo( "SKU1" ) }} 
{{ productInfo( "SKU2" ) }} 
```
becomes
```
{{ productInfo( "SKU1", preferredLanguage, mobile )  }}
{{ productInfo( "SKU2", preferredLanguage, mobile )  }}
```
Not that readable.
If we now decide to use one more variable in a macro we have to find _every_ usage of a macro and add it.
Not that refactorable.

Your point makes perfect sense if template becomes quite large and gets complex logic. But is it template anymore? Java is better place for complex logic, it provides better information hiding tools. And we make our template simple again and readable for designers first, not just developers.

Unless Pebble plans to become templating engine with templating engines writen in it, like PHP :laughing:

Anyway, I found that it's easy to achieve behavour I want by introducing custom tag for macro, which pushes normal scope instead of "local". Twig-like "with" seems also straightforward. Pebble's extension architecture is awesome, I like it.
