### ISSUE TITLE
unbescape dependency

### ISSUE THREAD

**Issue by mtdowling** [PebbleTemplates/pebble#428]
Related somewhat to #427 -- would it be at all possible to make unbescape an optional dependency or possibly an optional library that can be used alongside Pebble? I'm interested in using Pebble, but have no use case for escaping since I'm generating code, and pulling in unnecessary dependencies is a hassle for both use inside my company and when trying to build jlink applications.

**Comment by ebussieres** [comment]
unbescape is used by the EscapeFilter, which is enabled by default.

If I declare it optional, all other project which are currently using it will need to declare the dependency. So no, I can't make it optional. 

You can exclude this dependency in your pom if you need to.
