### ISSUE TITLE
[Question] Can I access a cookie by cookie name in .peb file?

### ISSUE THREAD

**Issue by hooni24** [PebbleTemplates/pebble#429]
Is there any way to access cookie object in .peb file?

I know it is possible to access cookies by {{ request.cookies }}. 
But I need to access a cookie by cookie name directly.

Just like {{ request.cookie["someCookiName"] }}.

If It can be, please let me know.

**Comment by ebussieres** [comment]
Please take a look at https://javaee.github.io/javaee-spec/javadocs/javax/servlet/http/HttpServletRequest.html

You'll need to iterate over the cookie arrays and retrieve the one you want
