### ISSUE TITLE
JDK 11 warning

### ISSUE THREAD

**Issue by vitalyster** [PebbleTemplates/pebble#430]
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.mitchellbosecke.pebble.attributes.MemberCacheUtils (file:/Users/vt/.gradle/caches/modules-2/files-2.1/io.pebbletemplates/pebble/3.0.8/b031f5ecd0ebcd44b9c82e0492bc7bcd09be02f3/pebble-3.0.8.jar) to method java.util.Collections$EmptySet.size()
WARNING: Please consider reporting this to the maintainers of com.mitchellbosecke.pebble.attributes.MemberCacheUtils
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

**Comment by ebussieres** [comment]
Do you have a test case ? What's your setup ? Are you using java modules ? What's your template ?

Please provide more information please.

Thanks

**Comment by vitalyster** [comment]
No, I'm not using modules, and it doesn't reproduced on small templates. Is it possible to catch the warning in debugger? If no, I will try to reduce my template to minimal example

**Comment by vitalyster** [comment]
Found the problem with `--illegal-access=debug`: obviously my template contain `if theSet.size > 0` call. With `if theSet | length > 0` warning is gone
