### ISSUE TITLE
How to process the Templates are stored in Database

### ISSUE THREAD

**Issue by umesh2k8** [PebbleTemplates/pebble#431]
Hi,

Need help/Suggestions please.

 All my templates are stored on MongoDB and need to pick templates and dynamically render the contents.

How to process the sub templates like Main.peb contains header.peb and footer.peb and body.peb.

All templates stored separately in Mongo Collections.

If single template we can get string and process, But something like this?

Please suggest on this plz.

Sorry for my bad english :)

Thankyou,
Umesha

**Comment by ebussieres** [comment]
You need to define a custom Loader. You need to implements that [class](https://github.com/PebbleTemplates/pebble/blob/master/pebble/src/main/java/com/mitchellbosecke/pebble/loader/Loader.java) and define it in your PebbleEngine

Ex.

```
new PebbleEngine.Builder()
        .loader(new DatabaseLoader())
        .build()
```
