### ISSUE TITLE
pebbletemplates.io is down

### ISSUE THREAD

**Issue by slandelle** [PebbleTemplates/pebble#437]

**Comment by ebussieres** [comment]
@hectorlf Can you take a look please ?

**Comment by hectorlf** [comment]
Sure. I haven't received any mails from the registrar, but I'll have a look.

**Comment by hectorlf** [comment]
Domain restored, will take a while until the DNS changes propagate.

Kind reminder: never effing ever but domains from GoDaddy

**Comment by cjbrooks12** [comment]
It's back up for me now. Domain.com is also crap, had nothing but problems anytime I've tried to use them.

Moved all my domains to Google Domains about a year ago, havent had any issues with them.

**Comment by slandelle** [comment]
Thanks!

**Comment by hectorlf** [comment]
Thanks for reporting it!
