### ISSUE TITLE
Spring : isAuthenticated()

### ISSUE THREAD

**Issue by damir78** [PebbleTemplates/pebble#439]
Hi Guys,

how can we call a function from pebble template?

for Example If we need something like this: 
"user Blah is logged in":

{% if org.springframework.security.core.context.SecurityContextHolder.getContext().getAuthentication().isAuthenticated()  %} user Blah is logged in {% endif %}"

Any suggestion how we can access SecurityContextHolder as static method call?

**Comment by damir78** [comment]
Looks like we should use https://github.com/hectorlf/pebble-spring-security-extension by @hectorlf ...

**Comment by hectorlf** [comment]
Thanks for the plug, @damir78 😅

The security extension does more or less that. You can have a look at it's code if you want to implement it yourself. TBH, the extension is a ripoff of Spring's JSP tags.
