### ISSUE TITLE
Spring petclinic with pebble

### ISSUE THREAD

**Issue by damir78** [PebbleTemplates/pebble#440]
Hi guys,

already invested too much hours in pebble templates.

I think it can be a good alternative for thymeleaf as template engine in real applications.

For example, we wanna write a simple login-registration with spring security (especially isAUthentifacted, hasRole etc) , errors, messages.  And we need search - there are definitly  a documentation and example leaks.

[edit]removed unnecessary stuff[/edit]
Yes, you should write examples if you wanna more popularity !! You can write your benchmarks again and again but you need make the important step- show us what we need )))

Write login-registration, write **PETCLINIC** https://projects.spring.io/spring-petclinic/  example !!

**Please, implement the standard functionality that need every java web developer and everyone can say- nice framework.** 

Regards

P.S. I did a benchmark last night :))) https://github.com/damir78/template-benchmark

**Comment by ebussieres** [comment]
There's already an example project here : https://github.com/PebbleTemplates/pebble-example-spring

**Comment by ebussieres** [comment]
Just added spring-clinic example in PebbleTemplates repository
