### ISSUE TITLE
JDK9 illegal reflective action operation warning

### ISSUE THREAD

**Issue by NatHerencia** [PebbleTemplates/pebble#441]
Starting with JRE9, when executing "((AccessibleObject) result).setAccessible(true);" in MemberCacheUtils.java:83, the JRE throws a warning telling that, in future versions, that access won't be allowed.

This is related with "new" JDK modules. If a module doesn't explicitly allow another module to access it by Reflection, then the JDK currently throws just a warning **but in the future it won't allow access**.

In order to see the issue, execute MapSyntaxTest.testForTag() method using JDK9 or greater.

`WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.mitchellbosecke.pebble.attributes.MemberCacheUtils (file:/proyectos/repositorios/pebble/pebble/target/classes/) to method java.util.HashMap$Node.getKey()
WARNING: Please consider reporting this to the maintainers of com.mitchellbosecke.pebble.attributes.MemberCacheUtils
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release`

Specifically, the warning is related to an old JDK bug ( https://stackoverflow.com/questions/12037489/cant-access-to-java-util-hashmapentry-with-modifiers-public-final ) and it can be solved by making a new implementation of Map.Entry interface because Map module, obviously, doesn't allow specifically to Pebble to access it by Reflection.

**Comment by ebussieres** [comment]
Thanks ! Gonna be in next release

**Comment by zimmi** [comment]
Hi! I noticed that this is not only a problem for `HashMap`s but also `Arrays::asList`, so I opened a PR which handles this problem (hopefully) for the more general case of inaccessible collection implementations: https://github.com/PebbleTemplates/pebble/pull/443.
