### ISSUE TITLE
Pebble3 and null values in a Map

### ISSUE THREAD

**Issue by electrotype** [PebbleTemplates/pebble#446]
Hello!

I'm upgrading to Pebble 3.

I use `strictVariables` to `true`. 

In Pebble 2, those would both result in an empty string being output (no exception thrown):

1. The "map" being `null`:
```
{{ map }}
```

2. The "map" being a valid object and "myKey" being an existing key pointing to a `null` value:
```
{{ map.myKey }}
```

In Pebble 3, it seems the first case is the same (no exception thrown):
```
{{ map }}
```

But I get a `AttributeNotFoundException` exception on:
```
{{ map.myKey }}
```

Is it possible to configure something to get the previous behavior back? 

I only want an exception when I'm trying *to call something* on a `null` value (using ".") or if a key doesn't exist, not when the final value is `null`.

**Comment by ebussieres** [comment]
Hi,

I don't think we can bring back that behaviour by configuration. We'll need to change some Attribute Resolver (aka com.mitchellbosecke.pebble.attributes.MapResolver). It seems that some unit tests was missing

**Comment by electrotype** [comment]
I created a PR: https://github.com/PebbleTemplates/pebble/pull/447
Let me know if you need something. Thanks.

**Comment by ebussieres** [comment]
It's gonna be available in next release. Meanwhile, you can use the SNAPSHOT

Just add this to your pom.xml and use version 3.0.11-SNAPSHOT

```
<repositories>
  <repository>
    <id>sonatype-public</id>
    <name>Sonatype Public</name>
    <url>https://oss.sonatype.org/content/groups/public</url>
    <snapshots>
      <enabled>true</enabled>
    </snapshots>
  </repository>
</repositories>
```
