### ISSUE TITLE
Dynamic HTML form elements

### ISSUE THREAD

**Issue by decebals** [PebbleTemplates/pebble#451]
I need to create an HTML form dynamically with Pebble.
The idea is that I have a generic entity that contains a list with parameters. Each parameter has a name and a type (integer, date, float, ...).
I want to generate a form for editing entity. For each parameter type I want to insert a different HTML input component.
Do anyone do that?

**Comment by cjbrooks12** [comment]
You could set up a separate template for each field type, and then dynamically `include` a template for each field.

[Reference](https://pebbletemplates.io/wiki/tag/include/#dynamic-include)

**Comment by ebussieres** [comment]
You can also take a look at the spring petclinic example [here](https://github.com/PebbleTemplates/spring-petclinic)

**Comment by jochen777** [comment]
I wrote a from-lib that does exactly this.
Here are examples for pebble templates: (don't be fooled by the extension .twig. It's actually pebble!)
https://github.com/jochen777/jWebformExample/tree/master/src/main/resources/templates/jwebform/common
And here is the lib:
https://github.com/jochen777/jWebForm
