### ISSUE TITLE
Pebble Security Issue

### ISSUE THREAD

**Issue by securityMB** [PebbleTemplates/pebble#454]
I have found a security issue in Pebble similar to #435. Do you provide a way to report it or privately (e.g. via email) or are you okay with releasing details in the public issue?

**Comment by ebussieres** [comment]
Please report it here

**Comment by securityMB** [comment]
Thank you for quick answer.

So Pebble blocks access to `getClass()` but there might be other ways to get direct access to instances of `java.lang.Class`. Some Java classes have `TYPE` static field whose value is instance of `java.lang.Class`. An example being: [`java.lang.Integer`](https://docs.oracle.com/javase/7/docs/api/java/lang/Integer.html).

So instead of using 

    {{ ''.getClass().forName('java.lang.Runtime')... }}

the attacker can use

    {{ (1).TYPE.forName('java.lang.Runtime')... }}

I believe that at least on of the following can be done to limit the risk:
* Check whether any method or field returns an instance of `java.lang.Class` and block it if it does,
* Block certain methods that are commonly used to execute arbitrary Java code. FreeMarker, for instance, has a file [`unsafeMethods.properties`](https://github.com/apache/freemarker/blob/2.3-gae/src/main/resources/freemarker/ext/beans/unsafeMethods.properties) with several dozen methods that are considered unsafe for templating.

**Comment by ebussieres** [comment]
I like the freeMarker approch ... could you make a PR for this ?

**Comment by securityMB** [comment]
@ebussieres I'd love to but I've never actually programmed in Java so I don't really feel confident about doing it right.

**Comment by ebussieres** [comment]
Gonna be fixed in next release
