### ISSUE TITLE
Allow override core operators

### ISSUE THREAD

**Issue by cnogueira** [PebbleTemplates/pebble#455]
As of right now operator overrides are disabled. This means that one cannot change the behaviour of operators like `==` or any others.

While the use cases might be very marginal I do have a use case for this: I need to make `==` operator less strict on the types of the arguments. e.g. 

```java
//  default behavior
1 == "1" // false

// desired behavior
1 == "1" // true
```

Problem is that by design everything can be extended or overridden but the unary & binary operators.

My idea is to add a flag to enable the operator overrides. So users can override core operators if they want to. i.e.
```java
@Override
  public List<BinaryOperator> getBinaryOperators() {
    List<BinaryOperator> operators = new ArrayList<>();

    operators.add(new BinaryOperatorImpl("==", 30, CustomEqualsExpression.class, Associativity.LEFT));

    return operators;
  }
```
where `CustomEqualsExpression.class` would be the override for the `==` core operator.

**Comment by slandelle** [comment]
IMHO, Pebble is a Java library and core operators should stick to Java semantics. Why not convert to String or Integer, or compare to correct value or write your own custom extension ?

**Comment by cnogueira** [comment]
Our application contains a live HTML editor which uses pebble behind the scenes to provide templating functionality.

we have some monetary amounts which are already localized (hence the string type) and we'd really want to enable our users to do stuff like `{% if amount > 10 %}`.

for us it's not acceptable to expect our users to know which placeholders contain localized amounts (i.e. strings) and which contain actual numbers (i.e. index, counts, etc)

I know it's a fairly edgy use case, but having this will really improve our users experience.

**Comment by ebussieres** [comment]
One of core feature if the extensibility of the language. I think it's a good addition to pebble. I'll take a look at the PR later this week.
