### ISSUE TITLE
ZonedDateTime to long (time millis) 

### ISSUE THREAD

**Issue by decebals** [PebbleTemplates/pebble#457]
I have a variable available in template `ZonedDateTime time`.
I need to get time millis (for some javascript sort). In Java, I can do it with `time.toInstant().toEpochMilli()`.
How can I achieve this in template?

**Comment by ebussieres** [comment]
```
{{ time.toInstant.toEpchMilli }}
```

**Comment by decebals** [comment]
@ebussieres 
Thanks!
