### ISSUE TITLE
Consider avoiding feature version in spring boot starter name

### ISSUE THREAD

**Issue by snicoll** [PebbleTemplates/pebble#459]
We've seen users in the community building 3rd party starters struggling how to prepare the migration to Spring Boot 2 and one way to handle both Spring Boot 1.x and 2.x for the same version was to create a separate starter with Spring Boot 2 in its name.

Spring Boot 1.x is now EOL so I suggest dropping support for it and use the opportunity to remove the second starter. In the future, I'd suggest applying [this naming recommendation](https://github.com/spring-projects/spring-boot/wiki/Building-On-Spring-Boot#naming).

**Comment by ebussieres** [comment]
Gonna be changed in next release. 

Thanks
