### ISSUE TITLE
PebbleTemplateAvailabilityProvider doesn't find template files from the classpath

### ISSUE THREAD

**Issue by kzmi** [PebbleTemplates/pebble#464]
Spring Boot : 2.1.7
pebble-spring-boot-starter : 3.1.0

PebbleTemplateAvailabilityProvider always fails to find the template files like:

* {classpath}/templates/index.pebble
* {classpath}/templates/error/404.pebble

In PebbleTemplateAvailabilityProvider.java, this code returns always false.
```
return resourceLoader.getResource(prefix + view + suffix).exists();
```

`resourceLoader` was `AnnotationConfigServletWebServerApplicationContext` in my app, and the getResource() needs "classpath:" prefix to find a template file.

Before commit 0229ac770f5b17317f79cb90f6523a23d5e1e617, PebbleTemplateAvailabilityProvider does so.
```
return resourceLoader
          .getResource(ResourceLoader.CLASSPATH_URL_PREFIX + prefix + view + suffix).exists();
```

If ResourceLoader.CLASSPATH_URL_PREFIX is not wanted in some cases, both `prefix + view + suffix` and `ResourceLoader.CLASSPATH_URL_PREFIX + prefix + view + suffix` should be tried.

**Comment by ebussieres** [comment]
If you take a look at others TemplateAvailabilityProvider, it's not necessary to add classpath prefix.

[Mustache](https://github.com/gome-zhaojiuyang/-spring-boot-/blob/master/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/mustache/MustacheTemplateAvailabilityProvider.java#L46)
[Thymeleaf](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/thymeleaf/ThymeleafTemplateAvailabilityProvider.java#L40)

**Comment by kzmi** [comment]
Mustache uses MustacheProperties.DEFAULT_PREFIX which has "classpath:" prefix.
https://github.com/gome-zhaojiuyang/-spring-boot-/blob/master/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/mustache/MustacheProperties.java#L31

Thymeleaf too.
https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/thymeleaf/ThymeleafProperties.java#L42

**Comment by ebussieres** [comment]
Oh my bad ... so we need to change the default prefix

**Comment by ebussieres** [comment]
As a workaround for now, you can define a pebble.prefix in your application.properties with classpath:/templates/

**Comment by ebussieres** [comment]
Gonna be fixed in next version
