### ISSUE TITLE
How to solve the conflict between client side and server side curly braces?

### ISSUE THREAD

**Issue by leolux** [PebbleTemplates/pebble#474]
Pebble can't distinguish between vue.js expressions and pebble expressions which might lead to problems.

1. What does pebble render when there is not data for the given expression?
2. Is it possible to tell the pebble engine to use a custom template sytanx for variables i.e. `<<name>>` instead of `{{name}}`?

**Comment by ebussieres** [comment]
1. If no data exists for a given expression, it will render nothing.
2.Yes you can. You can change the syntax using the PebbleEngine Builder like this

```
Syntax customSyntax = new Syntax.Builder()
    .setDelimiterPrintOpen("<<")
    .setDelimiterPrintClose(">>")
    ...
    .build();
new PebbleEngine.Builder()
     .syntax(customSyntax)
     .build();
```
