### ISSUE TITLE
cannot access list item directly

### ISSUE THREAD

**Issue by pschiffe** [PebbleTemplates/pebble#485]
Hello,

I'm sorry if this is my fault, but I have a template like this:
```
      "feedback_question_id": "{{ capturedFeedbackQuestionIds }}",
      "feedback_question_id": "{{ capturedFeedbackQuestionIds | first }}",
      "feedback_question_id": "{{ capturedFeedbackQuestionIds[1] }}",
```

And the processed output looks like this:
```
      "feedback_question_id": "[172583, 172583, 172583, 172583, 172584, 172585, 172586, 172587, 172587, 172587, 172587, 172587, 172588, 172589, 172590]",
      "feedback_question_id": "172583",
      "feedback_question_id": "",
```

Could you reproduce? I cannot get any specific item from that list:

`capturedFeedbackQuestionIds -> List(172583, 172583, 172583, 172583, 172584, 172585, 172586, 172587, 172587, 172587, 172587, 172587, 172588, 172589, 172590)`

Pebble version is 3.1. Thank you!

**Comment by pschiffe** [comment]
Thank you for your response. I'm using pebble from gatling, so I'm not sure how I can debug it much further, but I've asked there as well, maybe they'll give me some hints.

**Comment by ebussieres** [comment]
I suggest that you try to reproduce it in a unit test. You can have a look here on how to make a unit test with pebble 

https://github.com/PebbleTemplates/pebble/blob/master/pebble/src/test/java/com/mitchellbosecke/pebble/GetAttributeTest.java

**Comment by pschiffe** [comment]
It was actually a bug in Gatling: https://github.com/gatling/gatling/commit/f724395ed056739f9e7b9cf9f5dff003fe4442cd
Sorry for bothering and thank you for confirmation that it should work indeed!
