### ISSUE TITLE
Empty map in strict mode does not throw exception

### ISSUE THREAD

**Issue by BreadAndRoses95** [PebbleTemplates/pebble#491]
Hi, I'm currently using Pebble Version: 3.1.2 in strict mode.
When using a map as context, I was expecting an `AttributeNotFoundException` if the map was empty, in this case It just resolved to null. I think the expected behavior in strict mode would be to throw an Exception every time the key is not present, even if the map is actually empty. 

A quick fix to this would be to move [this part](https://github.com/PebbleTemplates/pebble/blob/ca9ebdc71f8c4a1f9115f94271b700edd51cbfd1/pebble/src/main/java/com/mitchellbosecke/pebble/attributes/MapResolver.java#L40):
``` java
if(context.isStrictVariables() && !object.containsKey(key)) {
      throw new AttributeNotFoundException(null, String.format(
          "Attribute [%s] of [%s] does not exist or can not be accessed and strict variables is set to true.",
          attributeNameValue.toString(), object.getClass().getName()),
          attributeNameValue.toString(), lineNumber, filename);
    }
```
above [this part](https://github.com/PebbleTemplates/pebble/blob/ca9ebdc71f8c4a1f9115f94271b700edd51cbfd1/pebble/src/main/java/com/mitchellbosecke/pebble/attributes/MapResolver.java#L25)
```java
  if (object.isEmpty()) {
      return new ResolvedAttribute(null);
    }
```
Thank you !

**Comment by ebussieres** [comment]
According to this test, it already throw an exception :

https://github.com/PebbleTemplates/pebble/blob/master/pebble/src/test/java/com/mitchellbosecke/pebble/GetAttributeTest.java#L127

**Comment by ebussieres** [comment]
Fixed in next version

**Comment by BreadAndRoses95** [comment]
Thanks for the reactivity :)
