### ISSUE TITLE
String emptiness test  

### ISSUE THREAD

**Issue by mboullouz** [PebbleTemplates/pebble#495]
Many thanks to maintainers for this wonderful project. 
Is it possible to change to method that tests for string emptiness `com.mitchellbosecke.pebble.extension.core.EmptyTest`  into something similar to Apache StringUtils.isBlank( ...) ?
This is the 6 lines used by StringUtils:
     `     if (cs == null || (strLen = cs.length()) == 0) { 
               return true;
        }` 
`for (int i = 0; i < strLen; i++) {  ` 
    `    if (!Character.isWhitespace(cs.charAt(i))) {  ` 
                `     return false;  ` 
             `      }  ` 
         `  } `

**Comment by ebussieres** [comment]
Currently, it's an empty test. If I add this feature, it's gonna be another test implementation named as BlankTest. I suggest that you add a custom BlankTest in your project.

**Comment by ebussieres** [comment]
Current implementation use this :

```
"".equals(value.trim());
```

If you have a blank string, it'll return true. Do you have a specific issue ?

**Comment by mboullouz** [comment]
Thank s for the reply,
I work in a project that should support different asian langs .
I read[ this link ](https://closingbraces.net/2008/11/11/javastringtrim/)that warn against Trim().

**Comment by ebussieres** [comment]
Can you submit an example please ? A simple test case would suffice

**Comment by ebussieres** [comment]
@mboullouz Did you have time to create a test case ?

**Comment by ebussieres** [comment]
I'll close this issue since you did not provide feedback. Of course, you can reopen this issue if you provide a test case.
