### ISSUE TITLE
Custom operator can't use external context

### ISSUE THREAD

**Issue by vlalykin** [PebbleTemplates/pebble#497]
I register a new operation "LIKE":

```java
public class MyExtension extends AbstractExtension {
    @Override
    public List<BinaryOperator> getBinaryOperators() {
        return Arrays.asList(
                new BinaryOperatorImpl("like", 20, LikeExpression.class, Associativity.LEFT)
        );
    }
}
```
I can only specify the class name LikeExpression. Its instance is created by the engine and there is no good way to inject some necessary data into the class instance. Filters have no such problem.

Now I see such context injection methods:
1. through a static variable of some class
2. through the context of template variables
3. when using spring extension - through SpringApplicationContext ("beans" variable). Similar to point (2), only the path to the goal is even longer

I suggest registering not a class, but a factory (or provider) of class instances:

```java
LikeExpressionInstanceFactory factory = new LikeExpressionInstanceFactory( ... ); /* the desired context is passed here */
new BinaryOperatorImpl("like", 20, factory, Associativity.LEFT);
```

These two methods can exist together without breaking backward compatibility. Registering a class can use a lambda factory:

```java
(clazz) -> clazz.newInstance ();
```

**Comment by vlalykin** [comment]
if you don't mind, I am ready to do PR

**Comment by ebussieres** [comment]
What data do you need to inject in LikeExpression class ?

**Comment by vlalykin** [comment]
cache instance for storing compiled regular expressions

**Comment by cjbrooks12** [comment]
I'd imagine this would improve performance slightly, too, as it would eliminate the need for reflection when evaluating operators

**Comment by ebussieres** [comment]
We can just change the BinaryOperatorImpl constructor. Instead of getting a 

```
Class<? extends BinaryExpression<?>> nodeClass,
```

We should directly pass the instance of the class. 
```
BinaryExpression<?> nodeClass,
```
We should do the same modification in UnaryOperatorImpl too

**Comment by vlalykin** [comment]
no, the parser every time creates a new instance of the class for each node in the tree

**Comment by vlalykin** [comment]
and initializes a new class (leftExpression, rightExpression, lineNumber)

**Comment by ebussieres** [comment]
My bad ... you're right

**Comment by vlalykin** [comment]
and the class itself is used as a marker to distinguish the filter expression and test expression from the rest of the expressions. I think this is not good.

it’s all easy to fix, you can pass the expression type to the constructor (for example, enum)

**Comment by vlalykin** [comment]
@ebussieres 
Hi!
I created PR. 
Have a look, please.

**Comment by vlalykin** [comment]
I used Java 8 syntax. Maybe I'm wrong? I did not find in the documentation whether pebble supports Java 7.
If compilation on Java 7 is required, let me know, please
