### ISSUE TITLE
Security vulnerability

### ISSUE THREAD

**Issue by pwntester** [PebbleTemplates/pebble#501]
Hi,

Im a security researcher working with Github Security Lab (https://securitylab.github.com/). As part of a security review of Template engines, we have identified a security vulnerability on Pebble. What would be the best way to privately report the details?

We recommend you create a private GitHub Security Advisory for these findings. This also allows you to invite the GHSL team to collaborate and further discuss these findings in private before they are published.

Thanks,
A

**Comment by ebussieres** [comment]
@pwntester Just created one and invited you. Thanks for the discretion.

**Comment by Marcono1234** [comment]
Has this vulnerability (GHSL-2020-050) actually been fixed? Based on the [blog post](https://securitylab.github.com/advisories/GHSL-2020-050-pebble/) of the GitHub Security Lab it sounds like this vulnerability still exists.
