### ISSUE TITLE
limit tag in for loops

### ISSUE THREAD

**Issue by ThanosFisherman** [PebbleTemplates/pebble#504]
Hi,

is there a `limit` tag like there is in Liquid templating that would allow me to exit a loop at specified index?

What I want: 
```
 {% for item in numbers limit:4 %}
    {{ item }}
  {% endfor %}
```

How I worked this around

```
 {% for item in numbers %}
   {% if loop.index <= 3 %}
      {{ item }}
   {% endif %}
 {% endfor %}
```

But my solution is too verbose and I don't like it. Any suggestions? Furthermore I'd enjoy having more tags like this for example `offset` maybe `break` or `continue` as well as ranges. 

Am I asking for too much for a template language?

**Comment by cjbrooks12** [comment]
Slice should help https://pebbletemplates.io/wiki/filter/slice/

**Comment by ThanosFisherman** [comment]
Slice works great if you already know the length of an array you are about to slice. But if you enter a number bigger than the array length in `toIndex` parameter then you get 

`.PEB Syntax Error: toIndex must be smaller than input size: 3 `

in contrast with `limit` which will give you what's already available up until the limit number. Therefore in my case if the array length is smaller than 4, `limit` would give me all the array elements.

My use case is to display the 4 most recent posts in my orchid website and my solution works but I was just wondering if there's something more idiomatic.

**Comment by ebussieres** [comment]
I think that we can change slice and take the collection size when the toIndex is greater than the collection size. That way, you can achieve what you want.

What do you think ?

**Comment by ThanosFisherman** [comment]
Yes that would work great for my case I think. Should you prefer to modify the slice operator instead of creating a new one, that I leave it up to you :)

**Comment by ebussieres** [comment]
Fix's gonna be available in next release
