### ISSUE TITLE
Accessing Spring Beans when using Pebble with WebFlux

### ISSUE THREAD

**Issue by huw0** [PebbleTemplates/pebble#512]
I'm using Spring Boot 2.3.0 with WebFlux and Pebble Spring Boot Starter 3.1.3.

As in the documentation I am attempting to access a Spring Bean using:

```
{{ beans.beanName }}
```
However this results in a stacktrace because the beans variable is not defined.

* The header of Beans.java makes reference to being only for Spring MVC
* It looks like the Beans object is only set within PebbleView and not PebbleReactiveView?

1. I've made this work locally by extending PebbleReactiveView to set this object. Is this an acceptable fix? Possibly this was not done originally to prevent blocking methods being called?
2. If this is intentional, I suggest amending the documentation to highlight that this is not available when using Pebble with WebFlux.

**Comment by ebussieres** [comment]
It's not intentional and has been forgotten. Reactive support is kind of new in Pebble. You can make a PR if you wish to fix this issue. Otherwise, I'll take a look at it

**Comment by huw0** [comment]
Thanks for your quick response. I will try and tidy up what I have in the next few days and open a PR.

**Comment by ebussieres** [comment]
@huw0 : Just made a PR here (https://github.com/PebbleTemplates/pebble/pull/513). You can take a look to check if it's missing something

**Comment by huw0** [comment]
Thanks, yes that looks good.

In order for complete feature parity with servlet, it may be worth also implementing the equivalent access to reactive request, response, session objects from ServerWebExchange.
However this is slightly out of scope for the issue and these are not needed in my particular use case.
