### ISSUE TITLE
Printing variables starting with `is` or `contains` causes unexpected token OPERATOR

### ISSUE THREAD

**Issue by pwolaq** [PebbleTemplates/pebble#518]
Hello!

One of my colleagues discovered, that if you try to print variable which starts with `is` or `contains` it will result in the following error:

> Unexpected token "OPERATOR" of value "is"

> Unexpected token "OPERATOR" of value "contains"

Examples to reproduce:

```
{{ is_active }}
```
```
{{ contains_value }}
```

**Comment by pwolaq** [comment]
Another interesting example:
```
{{ 2 is_even }}
```
> Test [_even] does not exist.

**Comment by ebussieres** [comment]
Same as #426
