### ISSUE TITLE
regexPrintClose failing under Windows unless implicit newline following {{ }}

### ISSUE THREAD

**Issue by aristotaloss** [PebbleTemplates/pebble#52]
Commit 11d31911b85a00ccfe042b8aa6465c14fc2f28c7 has caused an issue under Windows (8.1 x86_64) where the following would evaluate fine:

```
<h1>{{hello}}
</h1>
```

, but the following would fail:

```
<h1>{{hello}}</h1>
```

with the error:

```
com.mitchellbosecke.pebble.error.ParserException: Unexpected "}" (hello.peb:1)
```

This is because commit 11d31911b85a00ccfe042b8aa6465c14fc2f28c7 changed the newline character in LexerImpl to `String newline = Pattern.quote(System.lineSeparator());`. Having the old `\\n` (before the commit) works fine.

**Comment by Velocity-** [comment]
Not a problem at all. Glad I could be of help, and nice to see you've fixed it! Cheers :+1:
