### ISSUE TITLE
Is it possible to configure which core functionality is loaded per default?

### ISSUE THREAD

**Issue by pepperbob** [PebbleTemplates/pebble#520]
We're using pebble templates to generate short reference numbers that are usually 10 to 30 chars long. The way these reference numbers are composed must be highly configurable so we basically expose the required pebble templates to (administrative) users.

As not all functionality provided by pepple is useful for these cases I wonder if there's a way to unload core extensions to limit available functionality as much as possible for security reasons and some control what a user can actually do with the templates.

Any thoughts on this is much appreciated!

**Comment by ebussieres** [comment]
As of now, Pebble provides the following extension that cannot be removed 

- CoreExtension
- EscaperExtension
- i18nExtension
- AttributeResolverExtension

 It would need some adjustment in PebbleEngine for that. However, it is possible to override operators with the `allowOverrideCoreOperators` flag.

If there's a use case for that, I think that you can open a PR to allow the user to enable/disable some extensions

**Comment by pepperbob** [comment]
Sorry for coming back so late on this topic... 

So when using the `PebbleEngine.Builder` a ExtensionRegistry is created which registers amongst others the `CoreExtension` which itself then provides tags, filters, etc. that will be used in the templates.

As an example: I need to restrict my the setup so that some tags cannot be used.

Is your suggestion to control the creation of `ExtensionRegistry` (PebbleEngine:621) by providing a factory for it through which I would be able to register my own Version of `CoreExtension` - which might be an inherited version overwriting `getTokenParsers`?

This sounds feasible, hopefully it won't dilute pebbles configuration-API too much. I'll take care to provide a MR for this and we'll see.
