### ISSUE TITLE
May a content glitch in Wiki

### ISSUE THREAD

**Issue by tzwjkl** [PebbleTemplates/pebble#522]
https://github.com/PebbleTemplates/pebble/blob/76f35ebc21eb93c3bcd3ee689c1507b400c97185/wiki/operator/comparisons/index.html#L102

I don't think it should be here, what do you think?

![2020-07-21 21-27-25 的屏幕截图](https://user-images.githubusercontent.com/17105863/88060581-060a6200-cb99-11ea-8ab1-cccf99f9d516.png)

**Comment by tzwjkl** [comment]
And the keyword `class` seems to be missing behind modifier `public`, when I copied and pasted this sample code I noticed it.

https://github.com/PebbleTemplates/pebble/blob/76f35ebc21eb93c3bcd3ee689c1507b400c97185/wiki/guide/extending-pebble/index.html#L121
https://github.com/PebbleTemplates/pebble/blob/76f35ebc21eb93c3bcd3ee689c1507b400c97185/wiki/guide/extending-pebble/index.html#L148
https://github.com/PebbleTemplates/pebble/blob/76f35ebc21eb93c3bcd3ee689c1507b400c97185/wiki/guide/extending-pebble/index.html#L179

**Comment by cjbrooks12** [comment]
Good catch, yes these look like typos in the docs. Would you mind opening a PR for these changes? The ones you linked are from the generated site, the source docs pages are here: [comparisons.md](https://github.com/PebbleTemplates/pebble/blob/master/docs/src/orchid/resources/wiki/operator/comparisons.md), [extending-pebble.md](https://github.com/PebbleTemplates/pebble/blob/master/docs/src/orchid/resources/wiki/guide/extending-pebble.md).

**Comment by tzwjkl** [comment]
> Good catch, yes these look like typos in the docs. Would you mind opening a PR for these changes? The ones you linked are from the generated site, the source docs pages are here: [comparisons.md](https://github.com/PebbleTemplates/pebble/blob/master/docs/src/orchid/resources/wiki/operator/comparisons.md), [extending-pebble.md](https://github.com/PebbleTemplates/pebble/blob/master/docs/src/orchid/resources/wiki/guide/extending-pebble.md).

Okay, I will try, thanks for your guidance.
