### ISSUE TITLE
macro access to global context not working as documented?

### ISSUE THREAD

**Issue by vgrigoriu** [PebbleTemplates/pebble#524]
Reading the docs [here](https://pebbletemplates.io/wiki/tag/macro/#access-to-the-global-context) I tried to pass the whole context to a macro in the following template (where `user1` and `user2` are provided in the context passed to `template.evaluate()`):
```
{{ m1(_context) }}
{% macro m1(_context) %}
{{ user1.name }} + {{ user2.name }}"
{% endmacro %}
```

Compare with the following template that does not use a macro:
```
{{ user1.name }} + {{ user2.name }}
```

Using the same context, the first one evaluates to ` + ` while the second evaluates to `bugs + bunny`. Of course, I can pass the two variables explicitly:
```
{{ m2(user1, user2) }}
{% macro m2(user1, user2) %}
{{ user1.name }} + {{ user2.name }}
{% endmacro %}
```

But I'd like to understand why the first example did not work as I expected. The example in the docs uses `{% set foo = 'bar' %}`, maybe it's different for variables passed through the context when you call `template.evaluate()`? Also, if it makes any difference, I'm using `getLiteralTemplate` to load the templates and I'm on version 3.1.4.

**Comment by ebussieres** [comment]
It's missing the use of _context variable within macro. If doc contains a typo, can you create a PR ?

```
{{ m1(_context) }}
{% macro m1(_context) %}
  {{ _context.user1.name }} + {{ _context.user2.name }}"
{% endmacro %}
```

**Comment by vgrigoriu** [comment]
Sure, I can do that!

**Comment by vgrigoriu** [comment]
Is [this](https://github.com/PebbleTemplates/pebble/blob/master/docs/src/orchid/resources/wiki/tag/macro.md) the place to make this change?
