### ISSUE TITLE
Protecting from macro bombs

### ISSUE THREAD

**Issue by vgrigoriu** [PebbleTemplates/pebble#526]
Suppose I want to run Pebble with macros I don't control. Is there a way to control against macro bombs (by analogy with [zip bombs](https://en.wikipedia.org/wiki/Zip_bomb)) such as this?
```twig
{{ m9() }}
{% macro m0() %}1234567890{% endmacro %}
{% macro m1() %}{{m0()}}{{m0()}}{{m0()}}{{m0()}}{{m0()}}{{m0()}}{{m0()}}{{m0()}}{{m0()}}{{m0()}}{% endmacro %}
{% macro m2() %}{{m1()}}{{m1()}}{{m1()}}{{m1()}}{{m1()}}{{m1()}}{{m1()}}{{m1()}}{{m1()}}{{m1()}}{% endmacro %}
{% macro m3() %}{{m2()}}{{m2()}}{{m2()}}{{m2()}}{{m2()}}{{m2()}}{{m2()}}{{m2()}}{{m2()}}{{m2()}}{% endmacro %}
{% macro m4() %}{{m3()}}{{m3()}}{{m3()}}{{m3()}}{{m3()}}{{m3()}}{{m3()}}{{m3()}}{{m3()}}{{m3()}}{% endmacro %}
{% macro m5() %}{{m4()}}{{m4()}}{{m4()}}{{m4()}}{{m4()}}{{m4()}}{{m4()}}{{m4()}}{{m4()}}{{m4()}}{% endmacro %}
{% macro m6() %}{{m5()}}{{m5()}}{{m5()}}{{m5()}}{{m5()}}{{m5()}}{{m5()}}{{m5()}}{{m5()}}{{m5()}}{% endmacro %}
{% macro m7() %}{{m6()}}{{m6()}}{{m6()}}{{m6()}}{{m6()}}{{m6()}}{{m6()}}{{m6()}}{{m6()}}{{m6()}}{% endmacro %}
{% macro m8() %}{{m7()}}{{m7()}}{{m7()}}{{m7()}}{{m7()}}{{m7()}}{{m7()}}{{m7()}}{{m7()}}{{m7()}}{% endmacro %}
{% macro m9() %}{{m8()}}{{m8()}}{{m8()}}{{m8()}}{{m8()}}{{m8()}}{{m8()}}{{m8()}}{{m8()}}{{m8()}}{% endmacro %}
```
(This OOMs around `m7` on my machine.)

I'm thinking of several possible ways:
- let the caller disallow macros altogether - not ideal
- let the caller disallow macro uses in macros - not sure how this would be implemented
- let the caller set a limit for the size of the output and throw an exception once it's reached - maybe decorate the `Writer` passed by the caller with a wrapper that keeps count of how many bytes were written to it.

What do you think @ebussieres, is any of the above worth adding to the project? I'm happy to create PRs for any of them.

**Comment by ebussieres** [comment]
Yeah you can add this fonctionnality and add a parameter to enable/disable it in PebbleEngine
