### ISSUE TITLE
Explicitly setting the time zone to be used by date formatting

### ISSUE THREAD

**Issue by vgrigoriu** [PebbleTemplates/pebble#527]
Formatting of dates using the `date` filter uses the current default time zone, which means that the same template might render differently on different machines if they are on different time zones. (I discovered this via a unit test that passed locally but failed in Jenkins.)

I wonder if it would make sense to add an optional parameter to `date` that would be a time zone and would be passed to `DateFormat::setTimeZone`, for cases where you would want to e.g. make sure that a certain date is rendered in UTC?

**Comment by ebussieres** [comment]
Yeah sure. Would you mind opening a PR for this change ?
