### ISSUE TITLE
How to create Function

### ISSUE THREAD

**Issue by sysmat** [PebbleTemplates/pebble#537]
* ver: 3.1.4
* java: 1.8
* I was looking at https://pebbletemplates.io/wiki/guide/extending-pebble/
* building fat jar
* I got an error: `java.lang.Class cannot be cast to com.mitchellbosecke.pebble.extension.Function`
* scenario:

```java
public class DossiersPeb implements Function {

    @Override
    public Object execute(Map<String, Object> args, PebbleTemplate pt, EvaluationContext ec, int i) {
        String username = (String)args.get("username");				
        return username + " with func";
    }

    @Override
    public List<String> getArgumentNames() {
        List<String> names = new ArrayList<>();
        names.add("username");	
        return names;
    }  
}
```  

```java
public class CustomPebExtension extends AbstractExtension implements Extension{
        
    @Override    
    public Map<String, Function> getFunctions() {         
        Map map = new HashMap();
        map.put("dossiers", DossiersPeb.class);
        return map;         
    }                
}
```

```java
PebbleEngine pebble = new PebbleEngine.Builder()
                                                      .extension(new CustomPebExtension())
                                                      .newLineTrimming(false)
                                                      .build();

```
in template usage `{{ dossiers(user.username) }}`

**Comment by nicky9door** [comment]
In your extension, you should be putting an instance of your function instead of its class:

`public class CustomPebExtension extends AbstractExtension implements Extension{
        
    @Override    
    public Map<String, Function> getFunctions() {         
        Map map = new HashMap();
        map.put("dossiers", new DossiersPub());
        return map;         
    }                
}`

**Comment by sysmat** [comment]
@nicky9door thx, regards
