### ISSUE TITLE
Could not find pebble:io.pebbletemplates:3.1.4.

### ISSUE THREAD

**Issue by silvajrdj** [PebbleTemplates/pebble#540]
I saw the pebble tutorial and I want try to use it, but when I configure my gradle it runs:

repositories {
    mavenCentral()
    google()
    jcenter()

dependencies {
implementation "pebble:io.pebbletemplates:3.1.4"

> Could not find pebble:io.pebbletemplates:3.1.4.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/pebble/io.pebbletemplates/3.1.4/io.pebbletemplates-3.1.4.pom
       - https://dl.google.com/dl/android/maven2/pebble/io.pebbletemplates/3.1.4/io.pebbletemplates-3.1.4.pom
       - https://jcenter.bintray.com/pebble/io.pebbletemplates/3.1.4/io.pebbletemplates-3.1.4.pom
       - https://dl.bintray.com/kotlin/ktor/pebble/io.pebbletemplates/3.1.4/io.pebbletemplates-3.1.4.pom
       - https://dl.bintray.com/kotlin/kotlinx/pebble/io.pebbletemplates/3.1.4/io.pebbletemplates-3.1.4.pom
       - https://kotlin.bintray.com/kotlin-js-wrappers/pebble/io.pebbletemplates/3.1.4/io.pebbletemplates-3.1.4.pom

**Comment by slandelle** [comment]
Wrong coordinates: you inverted groupId and artifactId!

`implementation 'io.pebbletemplates:pebble:3.1.4'`

**Comment by silvajrdj** [comment]
Oh, Yes, You're right. It works now.  Thank you very much.
