### ISSUE TITLE
Provide support for Servlet 5.0

### ISSUE THREAD

**Issue by chkal** [PebbleTemplates/pebble#548]
Pebble depends on the Servlet API 2.5 at the moment. Servlet 5.0, which will be part of the Jakarta EE 9 release, migrated the javax.* to the new jakarta.* package namespace. It would be great to see a Pebble version that supports this new package namespace.

Are there any plans for this at the moment?

**Comment by ebussieres** [comment]
You can create a new loader implementation (aka a new ServletLoader based on Jakarta EE9) and use it in your project. 

If you want that to be added in pebble, just provide a pull request once this is done.

**Comment by chkal** [comment]
Thanks for the hint. I'll try to provide a corresponding pull request in the next days.
