### ISSUE TITLE
add a file extension that will be recognized as pebble

### ISSUE THREAD

**Issue by xenoterracide** [PebbleTemplates/pebble#553]
using pebble to generate non web files, would be useful to have an extension that could be used to also recognize as pebble, for example in intellij's plugin. This is more of a doc, spec, spread the word thing.

**Comment by ebussieres** [comment]
Not sure to understand. You can already change the suffix for pebble's template.

**Comment by xenoterracide** [comment]
an IDE can't recognize a file as a pebble template if it's not say, html.

**Comment by xenoterracide** [comment]
the point of this issue is to have a standard extension name so *any* ide could use that to recognize it. but if you're not willing feel free to close it.

**Comment by ebussieres** [comment]
If you are uaing spring boot, default extension is .pebble

https://github.com/PebbleTemplates/pebble/blob/74fdbec55aa5c576c24019ecc8da7fdd7bd2a048/pebble-spring/pebble-spring-boot-starter/src/main/java/com/mitchellbosecke/pebble/boot/autoconfigure/PebbleProperties.java#L11

**Comment by xenoterracide** [comment]
is this the default extension of pebble itself? does this mean that `getTemplate` with FileLoader does not require the extension when looking up the string?

**Comment by xenoterracide** [comment]
the intellij bug says that it's `.peb` that is supported by default, so by not documenting this there are already 2 different file extensions used.

**Comment by bjansen** [comment]
Most of the unit tests, documentation and Javadoc in this repo use the `.peb` extension, although it's not documented as the 'official' extension. I'm a little surprised you guys decided to use `.pebble` in the Spring Boot started actually.

**Comment by xenoterracide** [comment]
> you guys decided to use .pebble in the Spring Boot started actually

I don't know, but this sort of confusion is why I'm asking it to be documented.

**Comment by ebussieres** [comment]
Ok I'll change default extension suffix in spring boot to `.peb` in version 3.2

**Comment by bjansen** [comment]
Won't this break projects that don't customize the default settings when they upgrade to 3.2?

**Comment by ebussieres** [comment]
That's why I intend to make this change in 3.2.x and not in 3.1.x branch

**Comment by ebussieres** [comment]
Gonna be available in next release
