### ISSUE TITLE
How to access Servlet API in the template file？

### ISSUE THREAD

**Issue by CodePlayer** [PebbleTemplates/pebble#555]
How to access HttpServletRequest/HttpSession/ServletContext's API  in the template file？

In addition, when I implement `com.mitchellbosecke.pebble.extension.Function`, I also need to access `HttpServletRequest`.
How can I achieve this?

**Comment by ebussieres** [comment]
Are you using spring boot ? If so, there are already some objects defines by the SpringExtension.

Take a look at the end of this doc
https://pebbletemplates.io/wiki/guide/spring-boot-integration/

**Comment by CodePlayer** [comment]
@ebussieres  Sorry, I do NOT use Spring Boot, only Spring Framework.

**Comment by ebussieres** [comment]
Ok, if you need, you can use these 3 variables which are available in PebbleView (even if you don't use spring-boot)

  public static final String REQUEST_VARIABLE_NAME = "request";
  public static final String RESPONSE_VARIABLE_NAME = "response";
  public static final String SESSION_VARIABLE_NAME = "session";

Example in templates:

```
{{ request.contextPath }}
```

**Comment by CodePlayer** [comment]
@ebussieres  Thank you very much for your enthusiastic answer!
