### ISSUE TITLE
evaluate string?

### ISSUE THREAD

**Issue by xenoterracide** [PebbleTemplates/pebble#556]
is it possible to simply pass a template string to engine somehow? e.g. 

```java
var tmpl = engine.getTemplate("{{hello}}");
tmpl.evaluation(writer, Map.of("hello", "world");
```

**Comment by ebussieres** [comment]
Yes it is. All unit tests use that technique. 

For example
https://github.com/PebbleTemplates/pebble/blob/74fdbec55aa5c576c24019ecc8da7fdd7bd2a048/pebble/src/test/java/com/mitchellbosecke/pebble/CoreFunctionsTest.java#L95

**Comment by xenoterracide** [comment]
thanks, I'm guessing it's not possible to use the same engine for a different loader.
