### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by objectProgrammer** [PebbleTemplates/pebble#575]
Hello, I feel like there have been many fixes and additions worthy of being in a new stable release. Is there anything stopping a new release, or is it just that not enough has been changed? It could be a simple minor version increase to 3.1.5.

**Comment by ebussieres** [comment]
Yeah I'll try to do it soon. I'm just overwhelmed 😉

**Comment by ebussieres** [comment]
Release is in progress

**Comment by objectProgrammer** [comment]
Thanks!
