### ISSUE TITLE
CSRF Token 

### ISSUE THREAD

**Issue by GideonBrimleaf** [PebbleTemplates/pebble#578]
Hello!  Is there a way to put a CSRF token into a form in a Pebble template?  Thymeleaf has the ability to add a hidden input field to a form with a csrf token like so which is required by frameworks like Spring with Spring Security. 

```
<form method="post" action="/logout">
  <input type="hidden" name="${_csrf.parameterName}" value="${_csrf.token}" />
  <button id="logout-button" type="submit">Logout</button>
</form>
```

Thanks

**Comment by ebussieres** [comment]
Spring exposes a request attribute named _csrf. In order to access it you should with pebble-spring-boot-starter :

1- Enable exposeRequestAttributes:

In your application.properties, set `pebble.exposeRequestAttributes=false`

2- In your template:

```
<input type="hidden" name="${request.getAttribute('_csrf').parameterName}" value="${request.getAttribute('_csrf').token}" />
```

**Comment by GideonBrimleaf** [comment]
Thanks for the quick response!  Unfortunately I've tried a couple of different permutations but not getting the form to post successfully - I get a 403 error which I think means that Spring Security recognises the request but the CSRF token is not being picked up/recognised. 


1. I've set `pebble.exposeRequestAttributes=true` in my `application.properties` file
2. I've also tried to add it into my form like so:

```
<form  method="post" action="/logout">
  <input type="hidden" name="${request.getAttribute('_csrf').parameterName}" value="${request.getAttribute('_csrf').token}" />
  <button id="logout-button" type="submit">Logout</button>
</form>
```

The form successfully renders so I'm able to get Pebble to render correctly.  Interestingly if I try to expose the `request` attribute it doesn't show any data:

```
<form method="post" action="/logout">
  <input type="hidden" name="${request.getAttribute('_csrf').parameterName}" value="${request.getAttribute('_csrf').token}" />
  <button  id="logout-button" type="submit">Logout</button>
   <p>Request data is {{ request }}</p> {# Added! #}
</form>
```

Am I missing something else? It might be worth noting I'm running Kotlin with Spring and I've added the following dependencies to the project:

`build.gradle.kts`
```
dependencies {
        implementation("org.springframework.boot:spring-boot-starter-data-jpa")
	implementation("org.springframework.boot:spring-boot-starter-web")
	implementation("org.springframework.boot:spring-boot-starter-security")
	implementation("io.pebbletemplates:pebble-spring-boot-starter:3.1.5")
	implementation("org.jetbrains.kotlin:kotlin-reflect")
	implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")
	implementation("com.okta.spring:okta-spring-boot-starter:2.0.1")
	runtimeOnly("com.h2database:h2")
	testImplementation("org.springframework.boot:spring-boot-starter-test")
}
```

Thanks for your help!

**Comment by SharkFourSix** [comment]
> <form method="post" action="/logout">
>   <input type="hidden" name="${_csrf.parameterName}" value="${_csrf.token}" />
>   <button id="logout-button" type="submit">Logout</button>
> </form>

Do this to get it to work:

Include

```xml
<dependency>
    <groupId>io.pebbletemplates</groupId>
    <artifactId>pebble-spring-boot-starter</artifactId>
    <version>${pebble.version}</version>
</dependency>
```

External Properties (application.yml):

```yaml
pebble:
  exposeRequestAttributes: true
```

View:

```html
<form method="post" action="/logout">
  <input type="hidden" name="{{_csrf.parameterName}}" value="{{_csrf.token}}" />
  <button id="logout-button" type="submit">Logout</button>
</form>
```

**Comment by vitalyster** [comment]
How can I access this attribute when using `pebble-spring6` without autoconfiguration? I checked the auto configuration code and that still does not give me a clue

**Comment by vitalyster** [comment]
Found the answer myself: this is a base ViewResolver property so `viewResolver.setExposeRequestAttribute(true)` in my ViewResolver bean initialization did the trick
