### ISSUE TITLE
computing set variable

### ISSUE THREAD

**Issue by sysmat** [PebbleTemplates/pebble#579]
Is it possible to something like this:

```html
{% set count = 1 %}  
<ul>
{% for network in networks %}
    {%  count++ %}  
    <li>{{count}} {{ network.networkName }}</li>	
{% endfor %}
</ul>    
```
Regards

**Comment by fabriceci** [comment]
It's useless because you can retrieve the loop index: [https://pebbletemplates.io/wiki/tag/for](https://pebbletemplates.io/wiki/tag/for/)

```twig
{% for network in networks %}
    <li>{{loop.index}} {{ network.networkName }}</li>	
{% endfor %}
```

But for info, here is the corrected version of your code:

```twig
{% set count = 1 %}  
<ul>
{% for network in networks %}
    {% set count = count + 1 %}  
    <li>{{count}} {{ network.networkName }}</li>	
{% endfor %}
</ul>
```

**Comment by sysmat** [comment]
It was just a figurative, not just index, but computing values inside template

**Comment by fabriceci** [comment]
I was not sure it was figurative, that's why I also put the correction. My second example doesn't solve your issue? (If the computing is not light, I suggest you to create a custom function, it's pretty easy with Pebble)

**Comment by sysmat** [comment]
@fabriceci thx
