### ISSUE TITLE
[REQUEST] Make CacheKey class extendible

### ISSUE THREAD

**Issue by peppemas** [PebbleTemplates/pebble#604]
Hello, 

With the ability to build a custom cache it could be useful to create also a custom CacheKey but actually it's not possible.

https://github.com/PebbleTemplates/pebble/blob/aa43888a87901ea892258c02cee781d183d4a06b/pebble/src/main/java/com/mitchellbosecke/pebble/cache/CacheKey.java#L11

**Comment by ebussieres** [comment]
Gonna be available in next release (3.1.6)
