### ISSUE TITLE
Open Source Initiative Approved License

### ISSUE THREAD

**Issue by gebezs** [PebbleTemplates/pebble#605]
Introducing Pebble to enterprises is hard with custom license.

Any company who cares about their license usage usually allows only OSI Approved Licenses (https://opensource.org/licenses). This is mostly for legal reasons as the legal department knows those popular licenses and they pre-approve a subset of them. Getting something else approved is a nightmare.

Is it possible to change the license of Pebble to some popular and permissive license like Apache 2.0?

**Comment by slandelle** [comment]
@gebezs Pebble's license is BSD-3 clauses, cf https://opensource.org/licenses/BSD-3-Clause

It's 100% OSI Approved and compatible with Apache 2.

**Comment by gebezs** [comment]
Thanks for the prompt answer.

What puzzles me is the fact that type of license is not detected by Github. Meanwhile the `pebble-example-spring` repository's license is detected properly.

The https://github.com/PebbleTemplates/pebble repo:
![pebble-repo](https://user-images.githubusercontent.com/51337638/141253345-18775e33-2b54-4530-b5ef-db4dbc8694ad.png)

The https://github.com/PebbleTemplates/pebble-example-spring repo:
![pebble-example-spring-repo](https://user-images.githubusercontent.com/51337638/141253413-fdf1c650-8e7a-4e3f-9ca0-7f6b8bb7ea47.png)

As you can see the bottom right part of the image is different as `pebble-example-spring` shows the BSD-3 license type.

The difference between the the license are minimal:
https://raw.githubusercontent.com/PebbleTemplates/pebble/master/LICENSE
https://raw.githubusercontent.com/PebbleTemplates/pebble-example-spring/master/LICENSE

I assume there can be three issues:
1. The `pebble` repo's license file contains something which makes it incompatible with the BSD-3 license.
2. The license has some additional info in it or the formatting is not correct and for that it isn't detected.
3. Github's license detection has an issue.

The license detection page (https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository#detecting-a-license) states that 

> To have your license detected, simplify your LICENSE file and note the complexity somewhere else, such as your repository's README file.

Is it possible to change the LICENSE file to get detected by Github? It would probably make other users life simpler in the future.

**Comment by slandelle** [comment]
I guess you could send a pull request to update the license file with the exact wording from the OSI website. I expect GitHub would recognize it then.

**Comment by gebezs** [comment]
I started to experiment with it and the issue is the "Some rights reserved." part. When I change it to "All rights reserved." it gets recognized.

Can I change it to "All rights reserved."?

**Comment by slandelle** [comment]
> Can I change it to "All rights reserved."?

That’s for a maintainer of this project to say (I’m not one), hence my suggestion to send a PR.

**Comment by gebezs** [comment]
The PR #623 should solve this.
