### ISSUE TITLE
Does pebble have a function to make at least one input to be filled , even if all the attributs are optional

### ISSUE THREAD

**Issue by Hamza-Houzali** [PebbleTemplates/pebble#626]
i need to create a transformation request with peeble , and i have to send all my attributs as optional , but at least one of them have to filled in the request.

the first code is like :

{% if personne is not empty %}

    {% if personne.nom is not empty %}
      <nom>{{ personne.nom }}</nom>
    {% endif %}

    {% if personne.prenom is not empty %}
       <prenom>{{ personne.prenom }}</prenom>
    {% endif %}

{% endif %}
In my real code , i have at least a 100 attributs.

**Comment by ebussieres** [comment]
you can define a macro for that
