### ISSUE TITLE
Spring Boot Setup unclear / not working

### ISSUE THREAD

**Issue by AlEscher** [PebbleTemplates/pebble#637]
I have gradle project and am using the following dependency: `implementation 'io.pebbletemplates:pebble-spring-boot-starter:3.2.0'`.
I did not change any settings.
I have the following project structure:
```
src
--main
----java
------com.bla.code
----resources
------static
------templates
--------Base.pebble
--------DeliveryCollected.pebble
--------etc...
```
Afaiu, I should be able to get a template by doing 
```
this.engine = new PebbleEngine.Builder().build();
engine.getTemplate("DeliveryCollected");
```
According to your [documentation](https://pebbletemplates.io/wiki/guide/spring-boot-integration/) this should work out of the box, however I get the error `io.pebbletemplates.pebble.error.LoaderException: Could not find template "DeliveryCollected" (?:?)`

I am also unsure how I should address the template. In some examples when using HTML, the ending ".html" is specified, other times it isn't. This [documentation](https://pebbletemplates.io/wiki/guide/spring-boot-integration/) says the default extension is ".pebble", however your [repo](https://github.com/PebbleTemplates/pebble#breaking-changes-in-version-32x) says it is ".peb" (both do not work for me).

**Comment by ebussieres** [comment]
I'll adjust the documentation. Default extension is now `.peb`

I suggest that you take a look at https://github.com/PebbleTemplates/spring-petclinic for an example

**Comment by ebussieres** [comment]
Feel free to make a PR to update the documentation if you think something was unclear
