### ISSUE TITLE
SpringBoot version 2 use `pebble-legacy-spring-boot-starter` do not work for me!

### ISSUE THREAD

**Issue by mouday** [PebbleTemplates/pebble#644]
I ref doc

<img width="522" alt="image" src="https://user-images.githubusercontent.com/24365682/216820116-6a4849cf-0bbe-45ea-9524-9573e73be4fb.png">

SpringBoot version 2 use `pebble-legacy-spring-boot-starter` do not work for me!

SpringBoot Version

```xml
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.7.7</version>
		<relativePath/> <!-- lookup parent from repository -->
	</parent>
```

do not work for me!, not found template!

```xml
<dependency>
    <groupId>io.pebbletemplates</groupId>
    <artifactId>pebble-legacy-spring-boot-starter</artifactId>
    <version>3.2.0</version>
</dependency>
```

work for me!
```xml
<dependency>
    <groupId>io.pebbletemplates</groupId>
    <artifactId>pebble-spring-boot-starter</artifactId>
    <version>3.1.6</version>
</dependency>
```

**Comment by ebussieres** [comment]
In version 3.2.x, there is the following breaking change :

`Change default suffix to .peb instead of .pebble in spring boot autoconfiguration`

Did you change the default suffix or rename your templates ?

**Comment by mouday** [comment]
i test .peb  .pebble .html, all not work in pebble-legacy-spring-boot-starter-3.2.0, server return 404 not found!

**Comment by mouday** [comment]
thank you! I restart IDEA, it work!

```xml
<dependency>
	<groupId>io.pebbletemplates</groupId>
	<artifactId>pebble-legacy-spring-boot-starter</artifactId>
	<version>3.2.0</version>
</dependency>
```

application.properties

```bash
# 文件扩展名，默认 .peb
pebble.suffix=.html
```
