### ISSUE TITLE
docs: Table on installation page badly formatted 

### ISSUE THREAD

**Issue by vorburger** [PebbleTemplates/pebble#667]
https://pebbletemplates.io/wiki/guide/installation/

**Comment by ebussieres** [comment]
Not sure what's the problem. Feel free to submit a PR if needed. Installation guide page is here https://github.com/PebbleTemplates/pebble/blob/master/docs/src/orchid/resources/wiki/guide/installation.md

**Comment by vorburger** [comment]
https://pebbletemplates.io/wiki/guide/installation/ looks fine now.
