### ISSUE TITLE
Feature：Timestamp Filter

### ISSUE THREAD

**Issue by freshchen** [PebbleTemplates/pebble#673]
Converting dates and timestamps to and from each other is very common. 

I want to discuss whether we can add optional values ​​about timestamps in format  in DateFilter（format，existingFormat）

e.g.：
{{ time |  date(existingFormat='yyyy-MMMM-dd', format='timestamp') }}
{{ time |  date(existingFormat='timestamp', format='yyyy-MMMM-dd') }}

optional values：
timestamp
timestampMillisecond

**Comment by ebussieres** [comment]
Date filter already supports Temporal and older java.util.Date, so it should cover almost all use cases.

**Comment by ebussieres** [comment]
Just use {{ timestamp | date("MM/dd/yyyy HH:mm:ss") }}

**Comment by freshchen** [comment]
The Date constructor accepts milliseconds by default, so it does not support the second timestamp that is more commonly used in real life. This is very unintuitive for non-java programmers

If no changes are made, for date processing I have to define another timestamp filter to convert the timestamp into a millisecond timestamp, which is very troublesome to use.

The same goes for converting a formatted date into a timestamp with different time units.

**Comment by ebussieres** [comment]
You can use any Temporal date too ... such as a LocalDate, LocalDateTime, ZonedDateTime etc.

**Comment by freshchen** [comment]
Ok got it. I will add existingTimestamp parameter to my project
