### ISSUE TITLE
Report a Security Vulnerability

### ISSUE THREAD

**Issue by JLLeitschuh** [PebbleTemplates/pebble#680]
Hello,

My name is Jonathan Leitschuh, I'm a Principal Software Security Researcher at Chainguard. I'd like to report a potential security vulnerability in the Pebble template engine.

Would you be so kind as to enable GitHub Private Vulnerability Reporting? I'd like to privately disclose the details to you there.
https://docs.github.com/en/code-security/security-advisories/guidance-on-reporting-and-writing-information-about-vulnerabilities/privately-reporting-a-security-vulnerability

**Comment by ebussieres** [comment]
done

**Comment by JLLeitschuh** [comment]
Friendly ping, please take a look: https://github.com/PebbleTemplates/pebble/security/advisories/GHSA-7c6h-hmf9-7wj7

**Comment by JLLeitschuh** [comment]
@ebussieres friendly heads up that the disclosure deadline has lapsed and full disclosure of the unfixed vulnerability will occur within the next week.

**Comment by JLLeitschuh** [comment]
Publicly disclosed here: https://github.com/JLLeitschuh/security-research/security/advisories/GHSA-p75g-cxfj-7wrx

**Comment by ogomaemmanuel** [comment]
I think pebble has loaders that can be set when configuring the engine, StringLoader,ClassLoaders, FileLoaders etc, only file loader is supposed to read from anywhere within the filesystem. You can also disallow some extensions using registerExtensionCustomizer.
